<?php
$root = dirname(__DIR__);
function tr_read($path){global $root;$v=file_get_contents($root.'/'.$path);if(false===$v){fwrite(STDERR,"Cannot read $path\n");exit(1);}return $v;}
function tr_check($ok,$message){if(!$ok){fwrite(STDERR,"Third-review regression FAIL: $message\n");exit(1);}}
$install=tr_read('14-global-clinic-usp-integration/includes/class-gcu-install.php');
$repo=tr_read('14-global-clinic-usp-integration/includes/class-gcu-repository.php');
$rest=tr_read('14-global-clinic-usp-integration/includes/class-gcu-rest.php');
$front=tr_read('14-global-clinic-usp-integration/includes/class-gcu-frontend.php');
$future=tr_read('14-global-clinic-usp-integration/includes/class-gcu-future-intelligence.php');
$guards=tr_read('14-global-clinic-usp-integration/includes/class-gcu-future-guards.php');
$policy=tr_read('14-global-clinic-usp-integration/includes/class-gcu-policy.php');
$caps=tr_read('14-global-clinic-usp-integration/includes/class-gcu-capabilities.php');
$privacy=tr_read('14-global-clinic-usp-integration/includes/class-gcu-privacy.php');
$review=tr_read('14-global-clinic-usp-integration/includes/class-gcu-review80-hardening.php');
$obs=tr_read('14-global-clinic-usp-integration/includes/class-gcu-observability.php');
$contracts=tr_read('14-global-clinic-usp-integration/includes/class-gcu-contracts.php');
$status=tr_read('STATUS.md');
$release=tr_read('docs/RELEASE-EVIDENCE.md');
$ledger=tr_read('docs/REVIEW-80-THIRD-LEDGER-v1.4.1.md');
tr_check(false!==strpos($install,'public static function ready_for_runtime()')&&false!==strpos($install,'gcu_install_in_progress'),'Base runtime/install-lock boundary missing.');
tr_check(false!==strpos($install,'public static function ready_for_mutation(){return self::ready_for_runtime();}'),'Mutation readiness does not inherit runtime readiness.');
tr_check(substr_count($rest,'GCU_Install::ready_for_runtime()')>=4,'Base REST runtime fail-close coverage regressed.');
tr_check(false!==strpos($front,'GCU_Install::ready_for_runtime()')&&false!==strpos($front,"public, no-cache, max-age=0, must-revalidate"),'Frontend runtime/cache freshness boundary missing.');
tr_check(false!==strpos($future,'$base_ready = GCU_Install::ready_for_runtime();'),'Future runtime no longer inherits base runtime truth.');
tr_check(false!==strpos($install,'missing_columns')&&false!==strpos($install,'SHOW COLUMNS FROM'),'Base critical-column schema verification missing.');
tr_check(false!==strpos($future,'missing_columns')&&false!==strpos($future,'SHOW COLUMNS FROM'),'Future critical-column schema verification missing.');
tr_check(false!==strpos($future,'ensure_schema( $force_verify = false )')&&false!==strpos($install,'ensure_future_schema($force_verify=false)'),'Controlled Future force-verification plumbing missing.');
tr_check(false!==strpos($install,"if(!self::acquire_lock()){return new WP_Error('gcu_rollback_locked'")&&false!==strpos($install,"$maps['future_records']")&&false!==strpos($install,"$maps['future_reports']"),'Serialized Future-aware rollback missing.');
tr_check(false!==strpos($install,"'gcu_future_daily_governance','gcu_future_hourly_intelligence'"),'Future cron hooks are not cleared on deactivation.');
tr_check(false!==strpos($obs,"update_option('gcu_enabled',0,false)")&&false!==strpos($future,'update_option( self::SAFE_MODE_OPTION, 1, false )'),'Periodic schema-drift containment missing.');
tr_check(false!==strpos($repo,"b.review_due_at IS NULL OR b.review_due_at>UTC_TIMESTAMP()")&&false!==strpos($repo,'$all_claims=array()'),'Block freshness/linked-claim fail-close missing.');
tr_check(false!==strpos($repo,"review_due_at IS NULL OR review_due_at>UTC_TIMESTAMP()")&&false!==strpos($repo,"$u['review_due_at']=gmdate"),'Claim/copy review horizon fail-close missing.');
tr_check(false===strpos($repo,"${'all_claims'}"),'Correction artifact variable-variable syntax remains.');
tr_check(false!==strpos($caps,'if ( ! $allowed ) { return false; }'),'Authorization adapter may still elevate a native denial.');
tr_check(false!==strpos($policy,"'The platform charges 0% commission on approved clinic transactions.'")&&false===strpos($policy,"__( 'The platform charges 0% commission on approved clinic transactions.'"),'Canonical claim source truth is still locale-dependent.');
$exportStart=strpos($privacy,'public function export_data(');$captureStart=strpos($privacy,'public function capture_attribution(');$privacySubject=substr($privacy,$exportStart,$captureStart-$exportStart);
tr_check(false===strpos($privacySubject,'$_COOKIE'),'Privacy export/erase still reads the operator browser guest cookies.');
tr_check(false!==strpos($privacySubject,"gcu-copy-quality-reports")&&false!==strpos($privacySubject,'LIMIT 201 OFFSET %d')&&false!==strpos($privacySubject,'actor_hash=NULL'),'Future report export pagination/anonymization missing.');
tr_check(false!==strpos($future,'شناختی')&&false!==strpos($future,'هوية')&&false!==strpos($review,'شناختی')&&false!==strpos($review,'هوية'),'Urdu/Arabic sensitive-data rejection missing.');
tr_check(false!==strpos($guards,'gcu_future_scenario_note_private'),'Internal scenario notes may still become public.');
tr_check(false!==strpos($future,"consume_rate_limit( 'future-readiness', 60 )"),'Public readiness anti-abuse bound missing.');
tr_check(false!==strpos($rest,"mutation_rate('content')")&&false!==strpos($rest,"mutation_rate('workflow')"),'Base privileged mutation rate limits missing.');
tr_check(substr_count($future,'required_idempotency_key( $request )')>=3&&false!==strpos($future,"run_idempotent_command( 'future_record_write'")&&false!==strpos($future,"run_idempotent_command( 'future_claim_revalidate'")&&false!==strpos($future,"run_idempotent_command( 'future_report'"),'Future mutation durable idempotency missing.');
tr_check(false!==strpos($review,"X-GCU-Trace-ID"),'REST trace identifier header missing.');
tr_check(false!==strpos($rest,"public, no-cache, max-age=0, must-revalidate")&&false!==strpos($future,"public, no-cache, max-age=0, must-revalidate"),'Governed public REST data can be positively stale-cached.');
tr_check(false!==strpos($repo,"audit_lock_failed")&&false!==strpos($repo,"audit_write_failed")&&substr_count($repo,"update_option('gcu_enabled',0,false)")>=4,'Audit/outbox persistence failures are not fail-closed contained.');
tr_check(false!==strpos($contracts,'public_destination_health')&&false===strpos(substr($contracts,strpos($contracts,'public_destination_health')),"'owner'=>"),'Public destination DTO minimization regressed.');
tr_check(false!==strpos($status,'docs/REVIEW-80-THIRD-LEDGER-v1.4.1.md')&&false!==strpos($status,'exact current `main` SHA'),'Durable exact-current-head status truth missing.');
tr_check(false!==strpos($release,'third independent eighty-pass')&&false!==strpos($release,'fresh post-merge'),'Release evidence does not include third-review/exact-main policy.');
tr_check(false!==strpos($ledger,'43 defect-bearing rounds')&&false!==strpos($ledger,'| 80 |'),'Third eighty-pass defect ledger incomplete.');
tr_check(!file_exists($root.'/.github/workflows/file14-third-review-corrective-patch.yml'),'Temporary third-review corrective workflow remains.');
tr_check(!file_exists($root.'/scripts/apply-file14-third-review-corrections.py')&&!file_exists($root.'/scripts/apply-file14-third-review-deep-corrections.py')&&!file_exists($root.'/scripts/apply-file14-third-review-final-corrections.py')&&!file_exists($root.'/scripts/apply-file14-third-review-containment.py'),'Temporary third-review correction scripts remain.');
echo "Third-review regression tests: PASS\n";
