#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / '14-global-clinic-usp-integration'


def replace_once(path, old, new, label):
    text = path.read_text(encoding='utf-8')
    if old not in text:
        if new in text:
            print(f'{label}: already applied')
            return False
        raise SystemExit(f'{label}: expected source pattern not found')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')
    print(f'{label}: applied')
    return True

repo = P / 'includes/class-gcu-repository.php'
rest = P / 'includes/class-gcu-rest.php'
contracts = P / 'includes/class-gcu-contracts.php'
future = P / 'includes/class-gcu-future-intelligence.php'
fifth = P / 'includes/class-gcu-fifth-review-hardening.php'
frontend = P / 'includes/class-gcu-frontend.php'
main = P / 'global-clinic-usp-integration.php'
readme = P / 'readme.txt'

# R1 — validate token in permission phase, consume it atomically with the event mutation.
replace_once(
    repo,
    "public function consume_event_token($token,$purpose='measurement'){$ready=GCU_Install::ready_for_mutation();if(is_wp_error($ready)){return$ready;}$token=sanitize_text_field((string)$token);if(!preg_match('/^[a-f0-9\\-]{36}\\.[a-f0-9]{48}$/',$token)){return new WP_Error('gcu_event_token_invalid',__('A valid event token is required.','global-clinic-usp-integration'),array('status'=>403));}global$wpdb;$t=GCU_Install::tables();$done=$wpdb->query($wpdb->prepare(\"UPDATE {$t['event_tokens']} SET consumed_at=%s WHERE token_hash=%s AND purpose=%s AND consumed_at IS NULL AND expires_at>UTC_TIMESTAMP()\",current_time('mysql',true),hash('sha256',$token),sanitize_key($purpose)));return 1===$done?true:new WP_Error('gcu_event_token_expired',__('The event token expired or was already used.','global-clinic-usp-integration'),array('status'=>403));}",
    "public function validate_event_token($token,$purpose='measurement'){$ready=GCU_Install::ready_for_mutation();if(is_wp_error($ready)){return$ready;}$token=sanitize_text_field((string)$token);if(!preg_match('/^[a-f0-9\\-]{36}\\.[a-f0-9]{48}$/',$token)){return new WP_Error('gcu_event_token_invalid',__('A valid event token is required.','global-clinic-usp-integration'),array('status'=>403));}global$wpdb;$t=GCU_Install::tables();$wpdb->last_error='';$ok=$wpdb->get_var($wpdb->prepare(\"SELECT token_id FROM {$t['event_tokens']} WHERE token_hash=%s AND purpose=%s AND consumed_at IS NULL AND expires_at>UTC_TIMESTAMP() LIMIT 1\",hash('sha256',$token),sanitize_key($purpose)));if(''!==(string)$wpdb->last_error){return new WP_Error('gcu_event_token_read_failed',__('The event token could not be verified safely.','global-clinic-usp-integration'),array('status'=>503));}return $ok?true:new WP_Error('gcu_event_token_expired',__('The event token expired or was already used.','global-clinic-usp-integration'),array('status'=>403));}\npublic function consume_event_token($token,$purpose='measurement'){$ready=GCU_Install::ready_for_mutation();if(is_wp_error($ready)){return$ready;}$token=sanitize_text_field((string)$token);if(!preg_match('/^[a-f0-9\\-]{36}\\.[a-f0-9]{48}$/',$token)){return new WP_Error('gcu_event_token_invalid',__('A valid event token is required.','global-clinic-usp-integration'),array('status'=>403));}global$wpdb;$t=GCU_Install::tables();$done=$wpdb->query($wpdb->prepare(\"UPDATE {$t['event_tokens']} SET consumed_at=%s WHERE token_hash=%s AND purpose=%s AND consumed_at IS NULL AND expires_at>UTC_TIMESTAMP()\",current_time('mysql',true),hash('sha256',$token),sanitize_key($purpose)));return 1===$done?true:new WP_Error('gcu_event_token_expired',__('The event token expired or was already used.','global-clinic-usp-integration'),array('status'=>403));}",
    'R1 token validation split'
)
replace_once(repo, "public function record_event(array$d){", "public function record_event(array$d,$token=''){", 'R1 event token argument')
replace_once(
    repo,
    "if(!$this->begin_owned_transaction()){return new WP_Error('gcu_event_transaction_failed',__('The conversion event transaction could not start.','global-clinic-usp-integration'),array('status'=>503));}$ins=",
    "if(!$this->begin_owned_transaction()){return new WP_Error('gcu_event_transaction_failed',__('The conversion event transaction could not start.','global-clinic-usp-integration'),array('status'=>503));}if(''!==(string)$token){$consumed=$this->consume_event_token($token,'measurement');if(is_wp_error($consumed)){$this->rollback_owned_transaction();return$consumed;}}$ins=",
    'R1 atomic token consumption'
)
replace_once(rest, "GCU_Plugin::instance()->repository()->record_event($d)", "GCU_Plugin::instance()->repository()->record_event($d,sanitize_text_field((string)$r->get_header('X-GCU-Event-Token')))", 'R1 REST token handoff')
replace_once(rest, "return GCU_Plugin::instance()->repository()->consume_event_token(sanitize_text_field((string)$r->get_header('X-GCU-Event-Token')),'measurement');", "return GCU_Plugin::instance()->repository()->validate_event_token(sanitize_text_field((string)$r->get_header('X-GCU-Event-Token')),'measurement');", 'R1 permission validation only')

# R2 — remove INSERT IGNORE from conversion-event persistence so unrelated DB errors cannot masquerade as deduplication.
replace_once(
    repo,
    "$ins=$wpdb->query($wpdb->prepare(\"INSERT IGNORE INTO {$t['events']} (event_id,event_type,event_version,funnel_stage,destination_key,subject_hash,source_value,medium_value,campaign_value,ref_value,consent_state,occurred_at,created_at) VALUES (%s,'ClinicUSPFunnelEvent',1,%s,%s,%s,%s,%s,%s,%s,'granted',%s,%s)\",$id,$stage,$dest,$subject,$c['source'],$c['medium'],$c['campaign'],$c['ref'],current_time('mysql',true),current_time('mysql',true)));if(false===$ins){$this->rollback_owned_transaction();return new WP_Error('gcu_event_write_failed',__('The event could not be recorded.','global-clinic-usp-integration'),array('status'=>500));}",
    "$ins=$wpdb->query($wpdb->prepare(\"INSERT INTO {$t['events']} (event_id,event_type,event_version,funnel_stage,destination_key,subject_hash,source_value,medium_value,campaign_value,ref_value,consent_state,occurred_at,created_at) VALUES (%s,'ClinicUSPFunnelEvent',1,%s,%s,%s,%s,%s,%s,%s,'granted',%s,%s)\",$id,$stage,$dest,$subject,$c['source'],$c['medium'],$c['campaign'],$c['ref'],current_time('mysql',true),current_time('mysql',true)));if(false===$ins){$existing=$wpdb->get_var($wpdb->prepare(\"SELECT event_id FROM {$t['events']} WHERE event_id=%s LIMIT 1\",$id));if($existing){$ins=0;}else{$this->rollback_owned_transaction();return new WP_Error('gcu_event_write_failed',__('The event could not be recorded.','global-clinic-usp-integration'),array('status'=>500));}}",
    'R2 strict event insert'
)

# R3 — enforce destination-bound funnel invariant inside the repository, not only REST.
replace_once(
    repo,
    "$dest=sanitize_key(isset($d['destination'])?$d['destination']:'');$reg=GCU_Plugin::instance()->contracts()->destination_registry();if($dest&&!isset($reg[$dest])){return new WP_Error('gcu_invalid_destination',__('Unknown funnel destination.','global-clinic-usp-integration'),array('status'=>400));}if(('application_started'===$stage&&'doctor_onboarding'!==$dest)||('booking_started'===$stage&&'clinic'!==$dest)){return new WP_Error('gcu_stage_destination_mismatch',__('The funnel stage does not match its owner destination.','global-clinic-usp-integration'),array('status'=>400));}",
    "$dest=sanitize_key(isset($d['destination'])?$d['destination']:'');$reg=GCU_Plugin::instance()->contracts()->destination_registry();if(in_array($stage,array('cta_selected','destination_loaded','application_started','booking_started'),true)&&''===$dest){return new WP_Error('gcu_event_destination_required',__('This funnel stage requires a canonical destination.','global-clinic-usp-integration'),array('status'=>400));}if($dest&&!isset($reg[$dest])){return new WP_Error('gcu_invalid_destination',__('Unknown funnel destination.','global-clinic-usp-integration'),array('status'=>400));}if(('application_started'===$stage&&'doctor_onboarding'!==$dest)||('booking_started'===$stage&&'clinic'!==$dest)){return new WP_Error('gcu_stage_destination_mismatch',__('The funnel stage does not match its owner destination.','global-clinic-usp-integration'),array('status'=>400));}",
    'R3 repository funnel destination invariant'
)

# R4 — never store an empty/unstable pseudonymous measurement subject.
replace_once(
    repo,
    "$subject=GCU_Plugin::instance()->privacy()->event_subject_hash();if(!$this->begin_owned_transaction())",
    "$subject=GCU_Plugin::instance()->privacy()->event_subject_hash();if(!preg_match('/^[a-f0-9]{64}$/',(string)$subject)){return new WP_Error('gcu_event_subject_unavailable',__('A stable privacy-safe measurement subject could not be established.','global-clinic-usp-integration'),array('status'=>503));}if(!$this->begin_owned_transaction())",
    'R4 stable measurement subject fail-close'
)

# R5 — equal owner timestamps from different events are ambiguous, not silently discardable.
replace_once(
    contracts,
    "$existing=get_option(self::STATE_PREFIX.$key,array());$existing=is_array($existing)?$existing:array();if(!empty($existing['owner_occurred_at'])&&$owner_time<=(int)$existing['owner_occurred_at']){return true;}$url=",
    "$existing=get_option(self::STATE_PREFIX.$key,array());$existing=is_array($existing)?$existing:array();$existing_time=!empty($existing['owner_occurred_at'])?(int)$existing['owner_occurred_at']:0;$incoming_event_id=sanitize_text_field(isset($p['event_id'])?$p['event_id']:'');if($existing_time>$owner_time){return true;}if($existing_time===$owner_time&&$existing_time>0){if(!empty($existing['event_id'])&&hash_equals((string)$existing['event_id'],$incoming_event_id)){return true;}GCU_Observability::log('warning','owner_event_order_ambiguous',array('destination'=>$key,'owner_occurred_at'=>$owner_time));return new WP_Error('gcu_owner_event_order_ambiguous',__('Two different owner readiness events share the same occurrence time, so File 14 cannot choose an authoritative order safely.','global-clinic-usp-integration'),array('status'=>409));}$url=",
    'R5 owner event equal-time ambiguity'
)

# R6 — claim history INSERT IGNORE could hide non-duplicate failures.
replace_once(
    repo,
    "$ins=$wpdb->query($wpdb->prepare(\"INSERT IGNORE INTO {$t['claim_history']} (claim_key,row_version,status,claim_hash,reason,snapshot,actor_id,created_at) VALUES (%s,%d,%s,%s,%s,%s,%d,%s)\",$h['claim_key'],$h['row_version'],$h['status'],$h['claim_hash'],$h['reason'],$h['snapshot'],$h['actor_id'],$h['created_at']));if(false===$ins){$this->rollback_owned_transaction();return new WP_Error('gcu_claim_history_failed',__('Claim history could not be recorded safely.','global-clinic-usp-integration'),array('status'=>500));}",
    "$ins=$wpdb->query($wpdb->prepare(\"INSERT INTO {$t['claim_history']} (claim_key,row_version,status,claim_hash,reason,snapshot,actor_id,created_at) VALUES (%s,%d,%s,%s,%s,%s,%d,%s)\",$h['claim_key'],$h['row_version'],$h['status'],$h['claim_hash'],$h['reason'],$h['snapshot'],$h['actor_id'],$h['created_at']));if(false===$ins){$existing_history=$wpdb->get_row($wpdb->prepare(\"SELECT status,claim_hash,snapshot FROM {$t['claim_history']} WHERE claim_key=%s AND row_version=%d LIMIT 1\",$h['claim_key'],$h['row_version']),ARRAY_A);$same_history=is_array($existing_history)&&hash_equals((string)$existing_history['status'],(string)$h['status'])&&hash_equals((string)$existing_history['claim_hash'],(string)$h['claim_hash'])&&hash_equals(hash('sha256',(string)$existing_history['snapshot']),hash('sha256',(string)$h['snapshot']));if(!$same_history){$this->rollback_owned_transaction();return new WP_Error('gcu_claim_history_failed',__('Claim history could not be recorded safely.','global-clinic-usp-integration'),array('status'=>500));}}",
    'R6 strict claim history insert'
)

# R7 — mutation read-back is mandatory before commit.
replace_once(repo, "$result=$this->content_by_public_id($r['public_id']);if(!$this->commit_owned_transaction())", "$result=$this->content_by_public_id($r['public_id']);if(!is_array($result)||!isset($result['public_id'],$result['status'],$result['content_version'])||!hash_equals((string)$r['public_id'],(string)$result['public_id'])||'draft'!==(string)$result['status']||(int)$r['content_version']!==(int)$result['content_version']){$this->rollback_owned_transaction();return new WP_Error('gcu_content_readback_failed',__('The content version could not be verified before commit.','global-clinic-usp-integration'),array('status'=>503));}if(!$this->commit_owned_transaction())", 'R7 content read-back')
replace_once(repo, "$result=$this->record_by_public_id('placements',$r['public_id']);if(!$this->commit_owned_transaction())", "$result=$this->record_by_public_id('placements',$r['public_id']);if(!is_array($result)||!isset($result['public_id'],$result['status'])||!hash_equals((string)$r['public_id'],(string)$result['public_id'])||'planned'!==(string)$result['status']){$this->rollback_owned_transaction();return new WP_Error('gcu_placement_readback_failed',__('The placement could not be verified before commit.','global-clinic-usp-integration'),array('status'=>503));}if(!$this->commit_owned_transaction())", 'R7 placement read-back')
replace_once(repo, "$result=$this->record_by_public_id('experiments',$r['public_id']);if(!$this->commit_owned_transaction())", "$result=$this->record_by_public_id('experiments',$r['public_id']);if(!is_array($result)||!isset($result['public_id'],$result['status'])||!hash_equals((string)$r['public_id'],(string)$result['public_id'])||'proposed'!==(string)$result['status']){$this->rollback_owned_transaction();return new WP_Error('gcu_experiment_readback_failed',__('The experiment could not be verified before commit.','global-clinic-usp-integration'),array('status'=>503));}if(!$this->commit_owned_transaction())", 'R7 experiment read-back')

# R8 — Future quality/friction DB read failures fail closed instead of becoming empty/healthy analytics.
replace_once(future, "\tpublic static function rest_quality() {\n\t\treturn self::no_store_response( self::quality_score() );\n\t}\n", "\tpublic static function rest_quality() {\n\t\t$result = self::quality_score();\n\t\treturn is_wp_error( $result ) ? $result : self::no_store_response( $result );\n\t}\n", 'R8 quality REST error propagation')
replace_once(future, "\t\treturn self::no_store_response( self::friction_summary( $days ) );", "\t\t$result = self::friction_summary( $days );\n\t\treturn is_wp_error( $result ) ? $result : self::no_store_response( $result );", 'R8 friction REST error propagation')
replace_once(future, "\t\t$rows = $wpdb->get_results( \"SELECT funnel_stage,COUNT(*) total FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY) GROUP BY funnel_stage\", ARRAY_A );", "\t\t$wpdb->last_error = '';\n\t\t$rows = $wpdb->get_results( \"SELECT funnel_stage,COUNT(*) total FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY) GROUP BY funnel_stage\", ARRAY_A );\n\t\tif ( '' !== (string) $wpdb->last_error ) { return new WP_Error( 'gcu_future_quality_query_failed', __( 'Conversion quality data could not be read safely.', 'global-clinic-usp-integration' ), array( 'status' => 503 ) ); }", 'R8 quality event query fail-close')
replace_once(future, "\t\t$stale = (int) $wpdb->get_var( \"SELECT COUNT(*) FROM {$t['claims']} WHERE status='review_required' OR (status='active' AND review_due_at IS NOT NULL AND review_due_at<=UTC_TIMESTAMP())\" );\n\t\t$open_reports = (int) $wpdb->get_var( 'SELECT COUNT(*) FROM ' . self::tables()['reports'] . \" WHERE status IN ('open','reviewing')\" );", "\t\t$wpdb->last_error = '';\n\t\t$stale = (int) $wpdb->get_var( \"SELECT COUNT(*) FROM {$t['claims']} WHERE status='review_required' OR (status='active' AND review_due_at IS NOT NULL AND review_due_at<=UTC_TIMESTAMP())\" );\n\t\tif ( '' !== (string) $wpdb->last_error ) { return new WP_Error( 'gcu_future_quality_claim_query_failed', __( 'Claim freshness data could not be read safely.', 'global-clinic-usp-integration' ), array( 'status' => 503 ) ); }\n\t\t$wpdb->last_error = '';\n\t\t$open_reports = (int) $wpdb->get_var( 'SELECT COUNT(*) FROM ' . self::tables()['reports'] . \" WHERE status IN ('open','reviewing')\" );\n\t\tif ( '' !== (string) $wpdb->last_error ) { return new WP_Error( 'gcu_future_quality_report_query_failed', __( 'Copy-report data could not be read safely.', 'global-clinic-usp-integration' ), array( 'status' => 503 ) ); }", 'R8 quality claim/report query fail-close')
replace_once(future, "\t\t$rows = $wpdb->get_results( $wpdb->prepare( \"SELECT funnel_stage,COUNT(*) total FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) GROUP BY funnel_stage\", $days ), ARRAY_A );", "\t\t$wpdb->last_error = '';\n\t\t$rows = $wpdb->get_results( $wpdb->prepare( \"SELECT funnel_stage,COUNT(*) total FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL %d DAY) GROUP BY funnel_stage\", $days ), ARRAY_A );\n\t\tif ( '' !== (string) $wpdb->last_error ) { return new WP_Error( 'gcu_future_friction_query_failed', __( 'Conversion friction data could not be read safely.', 'global-clinic-usp-integration' ), array( 'status' => 503 ) ); }", 'R8 friction query fail-close')
replace_once(future, "\t\t$quality = self::quality_score();\n\t\t$parity = self::parity_status();", "\t\t$quality = self::quality_score();\n\t\tif ( is_wp_error( $quality ) ) { echo '<div class=\"notice notice-error\"><p>' . esc_html( $quality->get_error_message() ) . '</p></div>'; return; }\n\t\t$parity = self::parity_status();", 'R8 admin quality fail-close')

# R9 — anomaly/complaint query failures are experiment-safety breaches, not false healthy data.
replace_once(future, "\t\t$current = $wpdb->get_row( \"SELECT SUM(funnel_stage='cta_selected') selected,SUM(funnel_stage='destination_loaded') loaded FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 24 HOUR)\", ARRAY_A );\n\t\t$baseline = $wpdb->get_row( \"SELECT SUM(funnel_stage='cta_selected') selected,SUM(funnel_stage='destination_loaded') loaded FROM {$t['events']} WHERE occurred_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL 24 HOUR) AND occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 8 DAY)\", ARRAY_A );", "\t\t$wpdb->last_error = '';\n\t\t$current = $wpdb->get_row( \"SELECT SUM(funnel_stage='cta_selected') selected,SUM(funnel_stage='destination_loaded') loaded FROM {$t['events']} WHERE occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 24 HOUR)\", ARRAY_A );\n\t\t$current_error = (string) $wpdb->last_error;\n\t\t$wpdb->last_error = '';\n\t\t$baseline = $wpdb->get_row( \"SELECT SUM(funnel_stage='cta_selected') selected,SUM(funnel_stage='destination_loaded') loaded FROM {$t['events']} WHERE occurred_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL 24 HOUR) AND occurred_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 8 DAY)\", ARRAY_A );\n\t\t$baseline_error = (string) $wpdb->last_error;\n\t\tif ( '' !== $current_error || '' !== $baseline_error ) {\n\t\t\t$result = array( 'status' => 'query_failed', 'severity' => 'high', 'current_sample' => null, 'baseline_sample' => null, 'suppressed' => true, 'threshold' => GCU_Future_Policy::MIN_COHORT, 'checked_at' => gmdate( 'c' ) );\n\t\t\tupdate_option( self::LAST_ANOMALY_OPTION, $result, false );\n\t\t\tGCU_Observability::log( 'error', 'future_anomaly_query_failed', array() );\n\t\t\treturn $result;\n\t\t}", 'R9 anomaly query fail-safe')
replace_once(fifth, "\t\t$open_reports = (int) $wpdb->get_var(\n\t\t\t\"SELECT COUNT(*) FROM {$future_tables['reports']} WHERE status IN ('open','reviewing') AND created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY)\"\n\t\t);\n\t\t$breach = empty( $parity['ok'] )\n\t\t\t|| $destination_failure\n\t\t\t|| $open_reports >= 5", "\t\t$wpdb->last_error = '';\n\t\t$open_reports = (int) $wpdb->get_var(\n\t\t\t\"SELECT COUNT(*) FROM {$future_tables['reports']} WHERE status IN ('open','reviewing') AND created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY)\"\n\t\t);\n\t\t$report_query_failed = '' !== (string) $wpdb->last_error;\n\t\tif ( $report_query_failed ) { GCU_Observability::log( 'error', 'future_early_stop_report_query_failed', array() ); }\n\t\t$breach = empty( $parity['ok'] )\n\t\t\t|| $destination_failure\n\t\t\t|| $report_query_failed\n\t\t\t|| $open_reports >= 5", 'R9 early-stop report query fail-safe')

# R10 — prevent personalized shared-cache leakage and correctly mark en-US fallback content language/direction.
replace_once(frontend, "if($r||$shortcode_page){nocache_headers();header('Cache-Control: public, no-cache, max-age=0, must-revalidate',true);header('Pragma: no-cache',true);}}", "if($r||$shortcode_page){nocache_headers();if(is_user_logged_in()){header('Cache-Control: private, no-store, max-age=0, must-revalidate',true);}else{header('Cache-Control: public, no-cache, max-age=0, must-revalidate',true);header('Vary: Accept-Language, Cookie',false);}header('Pragma: no-cache',true);}}", 'R10 cache privacy boundary')
replace_once(frontend, "public function render_blocks($slot,$aud){$l=$this->current_locale();$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,$l);if(!$rows&&'en-US'!==$l){$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,'en-US');}if(!$rows){return'<section class=\"gcu-state gcu-state--empty\" role=\"status\" aria-live=\"polite\"><h2>'.esc_html(GCU_I18n::text('content_review_title',$l)).'</h2><p>'.esc_html(GCU_I18n::text('content_review_body',$l)).'</p></section>';}$h='<section class=\"gcu-grid gcu-grid--'.esc_attr($slot).'\">';", "public function render_blocks($slot,$aud){$l=$this->current_locale();$content_locale=$l;$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,$l);if(!$rows&&'en-US'!==$l){$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,'en-US');if($rows){$content_locale='en-US';}}if(!$rows){return'<section class=\"gcu-state gcu-state--empty\" role=\"status\" aria-live=\"polite\"><h2>'.esc_html(GCU_I18n::text('content_review_title',$l)).'</h2><p>'.esc_html(GCU_I18n::text('content_review_body',$l)).'</p></section>';}$h='<section class=\"gcu-grid gcu-grid--'.esc_attr($slot).'\" lang=\"'.esc_attr(GCU_I18n::language($content_locale)).'\" dir=\"'.esc_attr(GCU_I18n::direction($content_locale)).'\">';", 'R10 block fallback language')
replace_once(frontend, "private function render_faqs($root,$l){$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all',$l);if(!$items&&'en-US'!==$l){$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all','en-US');}if(!$items){return'';}$id=$root.'-faq-title';$h='<section class=\"gcu-faq\" aria-labelledby=\"'.esc_attr($id).'\"><h2 id=\"'.esc_attr($id).'\">'.", "private function render_faqs($root,$l){$content_locale=$l;$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all',$l);if(!$items&&'en-US'!==$l){$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all','en-US');if($items){$content_locale='en-US';}}if(!$items){return'';}$id=$root.'-faq-title';$h='<section class=\"gcu-faq\" lang=\"'.esc_attr(GCU_I18n::language($content_locale)).'\" dir=\"'.esc_attr(GCU_I18n::direction($content_locale)).'\" aria-labelledby=\"'.esc_attr($id).'\"><h2 id=\"'.esc_attr($id).'\">'.", 'R10 FAQ fallback language')

# Release identity: source correction cycle is v1.4.7; no DB schema change.
replace_once(main, ' * Version: 1.4.6', ' * Version: 1.4.7', 'v1.4.7 header')
replace_once(main, "define( 'GCU_VERSION', '1.4.6' );", "define( 'GCU_VERSION', '1.4.7' );", 'v1.4.7 constant')
replace_once(readme, 'Stable tag: 1.4.6', 'Stable tag: 1.4.7', 'v1.4.7 stable tag')
replace_once(readme, "Version 1.4.6 adds the eighth ten-round corrective hardening", "Version 1.4.6 added the eighth ten-round corrective hardening", 'historicalize v1.4.6 description')

# Prepend ninth-cycle changelog entry once.
text = readme.read_text(encoding='utf-8')
marker = '== Changelog ==\n'
entry = "== Changelog ==\n= 1.4.7 =\n* Ninth corrective cycle: ten sequential review/fix rounds over exact v1.4.6 PR-head repository truth.\n* Event tokens are validated in permission checks but consumed only inside the event transaction, so failed event writes do not burn the one-time token.\n* Conversion events and claim history no longer use broad INSERT IGNORE semantics; only verified duplicate identity is accepted.\n* Destination-bound funnel identity is enforced at repository level and unstable/empty measurement subjects fail closed.\n* Equal-timestamp owner readiness conflicts fail closed instead of silently discarding a distinct event.\n* Content, placement and experiment creation require authoritative read-back before commit.\n* Future quality/friction/anomaly and experiment early-stop complaint reads fail closed on database errors.\n* Logged-in File 14 pages are private/no-store; guest shared-cache responses vary by language/cookie; en-US fallback blocks/FAQs carry correct lang/dir semantics.\n* Base schema remains 10005 and Future schema remains 1.\n\n"
if '= 1.4.7 =' not in text:
    if marker not in text:
        raise SystemExit('Changelog marker missing')
    readme.write_text(text.replace(marker, entry, 1), encoding='utf-8')
    print('v1.4.7 changelog: applied')
else:
    print('v1.4.7 changelog: already applied')

print('Ninth-review source corrections complete.')
