#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
P="$ROOT/14-global-clinic-usp-integration"
fail=0
need(){ grep -RqsF "$1" "$2" || { echo "ROUND1 missing: $1 in $2" >&2; fail=1; }; }
forbid(){ if grep -RqsE "$1" "$2"; then echo "ROUND1 forbidden pattern: $1 in $2" >&2; fail=1; fi; }
need "Version: 1.4.1" "$P/global-clinic-usp-integration.php"
need "GCU_SCHEMA_VERSION', 10004" "$P/global-clinic-usp-integration.php"
need "SSH-F14-FUTURE-CTI-2026-v2.0" "$P/global-clinic-usp-integration.php"
need "GCU_FUTURE_SCHEMA_VERSION', 1" "$P/global-clinic-usp-integration.php"
need "GCU_Review80_Hardening" "$P/global-clinic-usp-integration.php"
need "F14-FUT-24" "$P/includes/class-gcu-future-policy.php"
need "gcu_future_records" "$P/includes/class-gcu-future-intelligence.php"
need "gcu_future_reports" "$P/includes/class-gcu-future-intelligence.php"
need "ENGINE=InnoDB" "$P/includes/class-gcu-install.php"
need "SHOW TABLE STATUS" "$P/includes/class-gcu-install.php"
need "SELECT GET_LOCK" "$P/includes/class-gcu-install.php"
need "snapshot_hash" "$P/includes/class-gcu-install.php"
need "START TRANSACTION" "$P/includes/class-gcu-install.php"
need "START TRANSACTION" "$P/includes/class-gcu-future-intelligence.php"
need "run_idempotent_command" "$P/includes/class-gcu-repository.php"
need "consumed_at IS NULL" "$P/includes/class-gcu-repository.php"
need "ON DUPLICATE KEY UPDATE counter=counter+1" "$P/includes/class-gcu-repository.php"
need "'audit-chain'" "$P/includes/class-gcu-repository.php"
need "process_inbox" "$P/includes/class-gcu-repository.php"
need "dispatch_outbox" "$P/includes/class-gcu-repository.php"
need "DATE_SUB(UTC_TIMESTAMP(),INTERVAL 10 MINUTE)" "$P/includes/class-gcu-repository.php"
need "gcu_destination_state_" "$P/includes/class-gcu-contracts.php"
need "may never elevate" "$P/includes/class-gcu-contracts.php"
need "sabri_shell_slot_ready_v1" "$P/includes/class-gcu-contracts.php"
need "strict_same_origin_url" "$P/includes/class-gcu-hardening.php"
need "rest_request_before_callbacks" "$P/includes/class-gcu-future-intelligence.php"
need "claim_freshness_sentinel" "$P/includes/class-gcu-future-intelligence.php"
need "early_stop_guard" "$P/includes/class-gcu-future-intelligence.php"
need "guardrails_valid" "$P/includes/class-gcu-review80-hardening.php"
need "verification_owner' => 'File 09 / File 00'" "$P/includes/class-gcu-future-policy.php"
forbid "wp_insert_post[[:space:]]*\(" "$P"
forbid "GCU_Policy::same_origin_url" "$P"
forbid "data-gcu-event-token" "$P"
forbid "onclick=|onload=|onerror=|javascript:" "$P"
if [ "$fail" -ne 0 ]; then exit 1; fi
echo "Fresh Review Round 1: PASS — architecture, canonical ownership, migration, concurrency, authorization, trust governance, reliability, queues, audit and destination fail-closed controls"
