#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
P="$ROOT/14-global-clinic-usp-integration"
fail=0
need(){ grep -RqsF "$1" "$2" || { echo "ROUND1 missing: $1 in $2" >&2; fail=1; }; }
forbid(){ if grep -RqsE "$1" "$2"; then echo "ROUND1 forbidden pattern: $1 in $2" >&2; fail=1; fi; }
need "Version: 1.4.9" "$P/global-clinic-usp-integration.php"
need "GCU_SCHEMA_VERSION', 10005" "$P/global-clinic-usp-integration.php"
need "SSH-F14-FUTURE-CTI-2026-v2.0" "$P/global-clinic-usp-integration.php"
need "GCU_FUTURE_SCHEMA_VERSION', 1" "$P/global-clinic-usp-integration.php"
need "GCU_Review80_Hardening" "$P/global-clinic-usp-integration.php"
need "GCU_Fifth_Review_Hardening" "$P/global-clinic-usp-integration.php"
need "pre_option_gcu_enabled" "$P/includes/class-gcu-fifth-review-hardening.php"
need "GCU_Install::verify_schema()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "GCU_Future_Intelligence::verify_schema()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "future_public_governance" "$P/includes/class-gcu-fifth-review-hardening.php"
need "gcu_conversion_event_identity_conflict" "$P/includes/class-gcu-fifth-review-hardening.php"
need "transactional_early_stop_guard" "$P/includes/class-gcu-fifth-review-hardening.php"
need "F14-FUT-24" "$P/includes/class-gcu-future-policy.php"
need "gcu_future_records" "$P/includes/class-gcu-future-intelligence.php"
need "gcu_future_reports" "$P/includes/class-gcu-future-intelligence.php"
need "ENGINE=InnoDB" "$P/includes/class-gcu-install.php"
need "SHOW TABLE STATUS" "$P/includes/class-gcu-install.php"
need "SELECT GET_LOCK" "$P/includes/class-gcu-install.php"
need "snapshot_hash" "$P/includes/class-gcu-install.php"
need "START TRANSACTION" "$P/includes/class-gcu-install.php"
need "begin_owned_transaction()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "run_idempotent_command" "$P/includes/class-gcu-repository.php"
need "consumed_at IS NULL" "$P/includes/class-gcu-repository.php"
need "ON DUPLICATE KEY UPDATE counter=counter+1" "$P/includes/class-gcu-repository.php"
need "'audit-chain'" "$P/includes/class-gcu-repository.php"
need "process_inbox" "$P/includes/class-gcu-repository.php"
need "dispatch_outbox" "$P/includes/class-gcu-repository.php"
need "DATE_SUB(UTC_TIMESTAMP(),INTERVAL 10 MINUTE)" "$P/includes/class-gcu-repository.php"
need "gcu_destination_state_" "$P/includes/class-gcu-contracts.php"
need "may never elevate" "$P/includes/class-gcu-contracts.php"
need "gcu_file14_placement_ready_v1" "$P/includes/class-gcu-contracts.php"
need "GCU_Companion_Adapters::placement_contract_ready" "$P/includes/class-gcu-contracts.php"
need "FILE00_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE01_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE07_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE07_MIN_CONTRACT" "$P/includes/class-gcu-companion-adapters.php"
need "DDD_Observability" "$P/includes/class-gcu-companion-adapters.php"
need "WCA_Observability" "$P/includes/class-gcu-companion-adapters.php"
need "owner_call" "$P/includes/class-gcu-companion-adapters.php"
need "companion_contract_exception" "$P/includes/class-gcu-companion-adapters.php"
need "FILE08_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE09_MIN_CONTRACT" "$P/includes/class-gcu-companion-adapters.php"
need "FILE19_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE20_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE24_MIN_VERSION" "$P/includes/class-gcu-companion-adapters.php"
need "FILE20_MIN_CONTRACT" "$P/includes/class-gcu-companion-adapters.php"
need "CentralPlanContract" "$P/includes/class-gcu-companion-adapters.php"
need "approved-clinic-cta" "$P/includes/class-gcu-companion-adapters.php"
need "slots-only" "$P/includes/class-gcu-companion-adapters.php"
need "contracts_ready" "$P/includes/class-gcu-companion-adapters.php"
need "module_state" "$P/includes/class-gcu-companion-adapters.php"
need "file01_manifest_current( $module, $expected_manifest )" "$P/includes/class-gcu-companion-adapters.php"
need "expected_routes" "$P/includes/class-gcu-companion-adapters.php"
need "contract-drift" "$P/includes/class-gcu-companion-adapters.php"
need "route_key" "$P/includes/class-gcu-companion-adapters.php"
need "spcrc/booted" "$P/includes/class-gcu-companion-adapters.php"
need "spcrc/governed_artifact_registry" "$P/includes/class-gcu-companion-adapters.php"
need "FILE25_MIN_CONTRACT" "$P/includes/class-gcu-companion-adapters.php"
need "SPF_Registry::register_manifest" "$P/includes/class-gcu-companion-adapters.php"
need "SPF_Registry::map_route" "$P/includes/class-gcu-companion-adapters.php"
need "SPF_Registry::register_contract" "$P/includes/class-gcu-companion-adapters.php"
need "sabri_shell_route_result_allowed" "$P/includes/class-gcu-companion-adapters.php"
need "sabri_shell_system_check_sections" "$P/includes/class-gcu-companion-adapters.php"
need "strict_same_origin_url" "$P/includes/class-gcu-hardening.php"
need "rest_request_before_callbacks" "$P/includes/class-gcu-future-intelligence.php"
need "claim_freshness_sentinel" "$P/includes/class-gcu-future-intelligence.php"
need "guardrails_valid" "$P/includes/class-gcu-review80-hardening.php"
need "verification_owner' => 'File 09 / File 00'" "$P/includes/class-gcu-future-policy.php"
forbid "wp_insert_post[[:space:]]*\(" "$P"
forbid "GCU_Policy::same_origin_url" "$P"
forbid "data-gcu-event-token" "$P"
forbid "onclick=|onload=|onerror=|javascript:" "$P"
if [ "$fail" -ne 0 ]; then exit 1; fi
echo "Fresh Review Round 1: PASS — architecture, runtime schema truth, canonical ownership, authorization, migration, concurrency, trust governance, reliability, queues, audit and destination fail-closed controls"
