#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
P="$ROOT/14-global-clinic-usp-integration"
fail=0
need(){ grep -RqsF "$1" "$2" || { echo "ROUND1 missing: $1 in $2" >&2; fail=1; }; }
forbid(){ if grep -RqsE "$1" "$2"; then echo "ROUND1 forbidden pattern: $1 in $2" >&2; fail=1; fi; }
need "Version: 1.4.7" "$P/global-clinic-usp-integration.php"
need "GCU_SCHEMA_VERSION', 10005" "$P/global-clinic-usp-integration.php"
need "SSH-F14-FUTURE-CTI-2026-v2.0" "$P/global-clinic-usp-integration.php"
need "GCU_FUTURE_SCHEMA_VERSION', 1" "$P/global-clinic-usp-integration.php"
need "GCU_Review80_Hardening" "$P/global-clinic-usp-integration.php"
need "GCU_Fifth_Review_Hardening" "$P/global-clinic-usp-integration.php"
need "GCU_CURRENT_REPOSITORY_ALIAS" "$P/global-clinic-usp-integration.php"
need "pre_option_gcu_enabled" "$P/includes/class-gcu-fifth-review-hardening.php"
need "GCU_Install::verify_schema()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "GCU_Future_Intelligence::verify_schema()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "future_public_governance" "$P/includes/class-gcu-fifth-review-hardening.php"
need "gcu_conversion_event_identity_conflict" "$P/includes/class-gcu-fifth-review-hardening.php"
need "transactional_early_stop_guard" "$P/includes/class-gcu-fifth-review-hardening.php"
need "future_early_stop_report_query_failed" "$P/includes/class-gcu-fifth-review-hardening.php"
need "apply_filters( 'gcu_authorize', false" "$P/includes/class-gcu-capabilities.php"
need "true === apply_filters" "$P/includes/class-gcu-capabilities.php"
need "F14-FUT-24" "$P/includes/class-gcu-future-policy.php"
need "gcu_future_records" "$P/includes/class-gcu-future-intelligence.php"
need "gcu_future_reports" "$P/includes/class-gcu-future-intelligence.php"
need "gcu_future_quality_query_failed" "$P/includes/class-gcu-future-intelligence.php"
need "gcu_future_friction_query_failed" "$P/includes/class-gcu-future-intelligence.php"
need "'status' => 'query_failed'" "$P/includes/class-gcu-future-intelligence.php"
need "ENGINE=InnoDB" "$P/includes/class-gcu-install.php"
need "SHOW TABLE STATUS" "$P/includes/class-gcu-install.php"
need "SELECT GET_LOCK" "$P/includes/class-gcu-install.php"
need "snapshot_hash" "$P/includes/class-gcu-install.php"
need "START TRANSACTION" "$P/includes/class-gcu-install.php"
need "begin_owned_transaction()" "$P/includes/class-gcu-fifth-review-hardening.php"
need "run_idempotent_command" "$P/includes/class-gcu-repository.php"
need "validate_event_token" "$P/includes/class-gcu-repository.php"
need "consume_event_token" "$P/includes/class-gcu-repository.php"
need "gcu_event_subject_unavailable" "$P/includes/class-gcu-repository.php"
need "gcu_content_readback_failed" "$P/includes/class-gcu-repository.php"
need "gcu_placement_readback_failed" "$P/includes/class-gcu-repository.php"
need "gcu_experiment_readback_failed" "$P/includes/class-gcu-repository.php"
need "consumed_at IS NULL" "$P/includes/class-gcu-repository.php"
need "ON DUPLICATE KEY UPDATE counter=counter+1" "$P/includes/class-gcu-repository.php"
need "'audit-chain'" "$P/includes/class-gcu-repository.php"
need "process_inbox" "$P/includes/class-gcu-repository.php"
need "dispatch_outbox" "$P/includes/class-gcu-repository.php"
need "DATE_SUB(UTC_TIMESTAMP(),INTERVAL 10 MINUTE)" "$P/includes/class-gcu-repository.php"
need "gcu_destination_state_" "$P/includes/class-gcu-contracts.php"
need "may never elevate" "$P/includes/class-gcu-contracts.php"
need "sabri_shell_slot_ready_v1" "$P/includes/class-gcu-contracts.php"
forbid "gcu_file20_slot_ready_v1" "$P/includes/class-gcu-contracts.php"
need "owner_occurred_at" "$P/includes/class-gcu-contracts.php"
need "gcu_owner_event_order_ambiguous" "$P/includes/class-gcu-contracts.php"
need "''!==\$owner_url" "$P/includes/class-gcu-contracts.php"
need "strict_same_origin_url" "$P/includes/class-gcu-hardening.php"
need "if ( '' === \$scope ) { return false; }" "$P/includes/class-gcu-hardening.php"
need "strlen( \$encoded ) > 1048576" "$P/includes/class-gcu-hardening.php"
need "event_identity_guard" "$P/includes/class-gcu-rest.php"
need "gcu_event_identity_conflict" "$P/includes/class-gcu-rest.php"
need "gcu_event_destination_required" "$P/includes/class-gcu-rest.php"
need "gcu_analytics_query_failed" "$P/includes/class-gcu-rest.php"
need "validate_event_token" "$P/includes/class-gcu-rest.php"
need "acquire_db_lock('subject-user:'" "$P/includes/class-gcu-privacy.php"
need "hash_equals(\$candidate,\$s)" "$P/includes/class-gcu-privacy.php"
need "\$remaining_meta" "$P/includes/class-gcu-privacy.php"
need "rest_request_before_callbacks" "$P/includes/class-gcu-future-intelligence.php"
need "claim_freshness_sentinel" "$P/includes/class-gcu-future-intelligence.php"
need "guardrails_valid" "$P/includes/class-gcu-review80-hardening.php"
need "verification_owner' => 'File 09 / File 00'" "$P/includes/class-gcu-future-policy.php"
forbid "wp_insert_post[[:space:]]*\(" "$P"
forbid "GCU_Policy::same_origin_url" "$P"
forbid "data-gcu-event-token" "$P"
forbid "onclick=|onload=|onerror=|javascript:" "$P"
if [ "$fail" -ne 0 ]; then exit 1; fi
echo "Fresh Review Round 1: PASS — v1.4.7 architecture, runtime schema truth, canonical ownership, explicit File00 authorization, migration, transactional token consume, strict persistence, read-back verification, DB-failure containment, stable privacy subject, queues and audit"
