#!/usr/bin/env python3
"""Sixth independent 80-pass exact-source review gate for File 14 v1.4.4.

This gate is repository evidence only. It does not prove staging, deployed-code,
live database, migration or operational state.
"""
from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'14-global-clinic-usp-integration'
def r(path): return (ROOT/path).read_text(encoding='utf-8')
loader=r('14-global-clinic-usp-integration/global-clinic-usp-integration.php')
install=r('14-global-clinic-usp-integration/includes/class-gcu-install.php')
repo=r('14-global-clinic-usp-integration/includes/class-gcu-repository.php')
rest=r('14-global-clinic-usp-integration/includes/class-gcu-rest.php')
contracts=r('14-global-clinic-usp-integration/includes/class-gcu-contracts.php')
hard=r('14-global-clinic-usp-integration/includes/class-gcu-hardening.php')
integrity=r('14-global-clinic-usp-integration/includes/class-gcu-integrity.php')
privacy=r('14-global-clinic-usp-integration/includes/class-gcu-privacy.php')
future=r('14-global-clinic-usp-integration/includes/class-gcu-future-intelligence.php')
fifth=r('14-global-clinic-usp-integration/includes/class-gcu-fifth-review-hardening.php')
policy=r('14-global-clinic-usp-integration/includes/class-gcu-policy.php')
caps=r('14-global-clinic-usp-integration/includes/class-gcu-capabilities.php')
front=r('14-global-clinic-usp-integration/includes/class-gcu-frontend.php')
obs=r('14-global-clinic-usp-integration/includes/class-gcu-observability.php')
admin=r('14-global-clinic-usp-integration/includes/class-gcu-admin.php')
future_policy=r('14-global-clinic-usp-integration/includes/class-gcu-future-policy.php')
future_i18n=r('14-global-clinic-usp-integration/includes/class-gcu-future-i18n.php')
css=r('14-global-clinic-usp-integration/assets/css/global-clinic-usp-integration.css')
future_css=r('14-global-clinic-usp-integration/assets/css/gcu-future-intelligence.css')
js=r('14-global-clinic-usp-integration/assets/js/global-clinic-usp-integration.js')
uninstall=r('14-global-clinic-usp-integration/uninstall.php')
status=r('STATUS.md')
release=r('docs/RELEASE-EVIDENCE.md')
trace=r('docs/REQUIREMENTS-TRACEABILITY.md')
quality=r('scripts/quality.sh')
workflow=r('.github/workflows/file14-quality.yml')
fresh=r('.github/workflows/file14-fresh-reviews.yml')
build=r('scripts/build.py')

checks=[]
def add(label, ok): checks.append((label,bool(ok)))

add('01 exact sixth-review release identity', 'Version: 1.4.4' in loader and "GCU_VERSION', '1.4.4" in loader and "GCU_SCHEMA_VERSION', 10005" in loader)
add('02 governing File14 and Future plan identities', 'SSH-F14-PLAN-2026-v1.0' in loader and 'SSH-F14-FUTURE-CTI-2026-v2.0' in loader)
add('03 active public blocks re-check File20 slot readiness at request time', 'placement_ready($row)' in repo)
add('04 File07 remains doctor-directory destination owner', "'doctor_directory'=>array('owner'=>'File 07'" in contracts)
add('05 File08 remains clinic destination owner', "'clinic'=>array('owner'=>'File 08'" in contracts)
add('06 File09 remains onboarding destination owner', "'doctor_onboarding'=>array('owner'=>'File 09'" in contracts)
add('07 File00 authorization adapter remains fail-closed', 'authorization_adapter_available' in caps and '! self::authorization_adapter_available()' in caps)
add('08 stable File14 privacy HMAC identity exists', 'PRIVACY_KEY_OPTION' in integrity and 'user_subject_hash' in integrity and 'future_actor_hash' in integrity)
add('09 stable File14 audit HMAC and legacy rehash migration exist', 'AUDIT_KEY_OPTION' in integrity and 'migrate_audit_chain' in integrity and 'legacy_audit_row_hash' in integrity)
add('10 invalid audit chain enters containment', 'audit_chain_integrity_failed' in obs and "update_option('gcu_enabled',0,false)" in obs)
add('11 admin success paths require mandatory audit persistence', 'Repair completed but its mandatory audit record failed' in admin and 'Rollback completed but its mandatory audit record failed' in admin)
add('12 safe-mode repair force-verifies Future schema', 'ensure_schema(true)' in admin)
add('13 shared nested owner transaction manager exists', all(x in repo for x in ('begin_owned_transaction','commit_owned_transaction','rollback_owned_transaction')))
add('14 audit-chain named lock is retained through owner transaction', 'transaction_audit_lock' in repo and 'release_transaction_audit_lock' in repo and "acquire_db_lock('audit-chain'" in repo)
add('15 Future claim freshness/revalidation and early stop use owner transactions', 'begin_owned_transaction()' in future and 'commit_owned_transaction()' in future and 'begin_owned_transaction()' in fifth)
add('16 idempotency keys are request-payload bound', 'request_hash' in repo and 'gcu_idempotency_payload_conflict' in repo and 'request_fingerprint' in hard)
add('17 command completion participates in owner transaction', 'run_idempotent_command' in repo and 'begin_owned_transaction()' in repo and "status='complete'" in repo)
add('18 stale install option lock recovery checks authoritative DB lock', 'install_lock_active' in install and 'IS_USED_LOCK' in install and 'stale_install_lock_recovered' in install)
add('19 base lifecycle cleanup drains bounded batches and warns on backlog', 'delete_batches' in repo and 'lifecycle_cleanup_backlog' in repo)
add('20 privacy export/erase uses stable user and Future actor identities', 'GCU_Integrity::user_subject_hash' in privacy and 'GCU_Integrity::future_actor_hash' in privacy)
add('21 inbound owner readiness/policy state is read-back verified before acknowledgement', 'persist_option_exact' in contracts and 'gcu_owner_state_persist_failed' in contracts and 'gcu_policy_revalidation_persist_failed' in contracts)
add('22 integrity migration checks SQL writes and durable migration marker', 'gcu_integrity_migration_state_failed' in integrity and '1!==$changed' in integrity.replace(' ',''))
add('23 rollback does not restore forward-only integrity keys/migration state', 'GCU_Integrity::AUDIT_KEY_OPTION' not in install[install.find('capture_snapshot'):install.find('safe_error_record')] if 'capture_snapshot' in install and 'safe_error_record' in install else False)
add('24 rate-limit counter read failure fails closed', 'gcu_rate_limit_read_failed' in repo)
add('25 conversion event and CTA owner outbox use one owner transaction', 'gcu_event_transaction_failed' in repo and 'gcu_event_outbox_failed' in repo and 'commit_owned_transaction' in repo)
add('26 CTA outbox persistence cannot silently succeed', 'gcu_event_outbox_failed' in repo and "publish_event('ClinicUSPCTASelected.v1'" in repo)
add('27 Future report creation uses stable actor identity and atomic audit/event', 'GCU_Integrity::future_actor_hash' in future and 'gcu_future_report_governance_failed' in future and "publish_event('ClinicUSPCopyQualityReported.v1'" in future)
add('28 Future report resolution is state-plus-audit atomic', 'gcu_future_report_update_failed' in future and "audit('copy_quality_report_updated'" in future and 'commit_owned_transaction' in future)
add('29 Future governed record create/update is state-plus-audit atomic', 'gcu_future_record_transaction_failed' in future and "audit('future_record_updated'" in future and "audit('future_record_created'" in future)
add('30 all early-stop entry paths delegate to transactional implementation', 'GCU_Fifth_Review_Hardening::transactional_early_stop_guard' in future)
add('31 Future admin query APIs expose stable cursor pagination', 'reports_page' in future and 'records_page' in future and 'next_cursor' in future)
add('32 Future lifecycle cleanup drains bounded batches and warns on backlog', 'future_lifecycle_cleanup_backlog' in future and 'for($i=0;$i<10;$i++)' in future.replace(' ',''))
add('33 measurement token is JIT and single-use', '/event-token' in rest and 'consumed_at IS NULL' in repo and 'tokenEndpoint' in js)
add('34 database rate limiting remains atomic', 'ON DUPLICATE KEY UPDATE counter=counter+1' in repo)
add('35 outbox retry and dead-letter lifecycle remain', 'dispatch_outbox' in repo and 'next_attempt_at' in repo and "'dead'" in repo)
add('36 inbox dedupe/retry/stale-lock recovery remain', 'process_inbox' in repo and 'payload_hash' in repo and 'INTERVAL 10 MINUTE' in repo)
add('37 audit full/recent-tail verification remains', 'verify_audit_chain' in repo and 'recent_tail' in repo and 'anchor_missing' in repo)
add('38 base/Future schema verification includes InnoDB and required columns', 'ENGINE=InnoDB' in install and 'SHOW COLUMNS' in install and 'SHOW COLUMNS' in future)
add('39 rollback snapshot/hash/verification remains governed', 'gcu_rollback_snapshot' in install and 'snapshot_hash' in install and 'rollback' in install.lower())
add('40 uninstall remains non-destructive by default with dual purge guards', 'GCU_ALLOW_PURGE' in uninstall and 'gcu_purge_on_uninstall' in uninstall)
add('41 strict same-origin validation checks scheme host effective port and userinfo', all(x in hard for x in ('strict_same_origin_url','effective_port',"isset( $target['user'] )","isset( $target['pass'] )")))
add('42 public destination DTO remains minimized', 'public_destination($key)' in contracts and "'owner'=>" not in contracts.split('public function public_destination($key)',1)[1].split('public function public_destination_health',1)[0])
add('43 owner destination readiness has bounded freshness', 'time()-DAY_IN_SECONDS' in contracts.replace(' ',''))
add('44 File20 remains sole shell/navigation owner without duplicate fallback', 'sabri_shell_back_home_controls' in front and 'data-gcu-shell-fallback' not in front)
add('45 File25 remains presentation boundary, not domain truth', 'File 25-compatible classes/tokens' in trace and 'visual-system truth' in trace)
add('46 Global Privacy Control is honored', 'HTTP_SEC_GPC' in privacy)
add('47 Save-Data/reduced-data is honored', 'HTTP_SAVE_DATA' in privacy and 'low_bandwidth_requested' in privacy)
add('48 sensitive routes are excluded from measurement', 'is_sensitive_path' in privacy)
add('49 attribution is restricted to File14 acquisition routes', 'is_file14_acquisition_route' in privacy)
add('50 campaign values are sanitized and bounded', 'sanitize_campaign' in policy and 'campaign_value_is_sensitive' in policy)
add('51 measurement requires explicit consent', 'measurement_allowed' in privacy and 'analytics_consent' in privacy)
add('52 WordPress privacy export and erasure remain registered', 'wp_privacy_personal_data_exporters' in privacy and 'wp_privacy_personal_data_erasers' in privacy)
add('53 funnel small cohorts are suppressed', 'suppressed_stages' in repo)
add('54 Future quality/anomaly small cohorts are suppressed', 'sample_count' in future and 'current_sample' in future and 'baseline_sample' in future)
add('55 FAQ aggregates reject sensitive/direct identifiers', 'question_contains_sensitive_data' in r('14-global-clinic-usp-integration/includes/class-gcu-review80-hardening.php'))
add('56 experiment guardrails and sensitive profiling block remain', 'guardrails_valid' in r('14-global-clinic-usp-integration/includes/class-gcu-review80-hardening.php') and 'sensitive_sampling' in future_policy)
add('57 experiment end date remains bounded to 90 days', '90*DAY_IN_SECONDS' in repo.replace(' ',''))
add('58 claim freshness sentinel remains active', 'claim_freshness_sentinel' in future)
add('59 active blocks fail closed on stale/missing linked claims', '$valid=$this->public_claims($all_claims)' in repo.replace(' ',''))
add('60 zero-commission rule remains exact', "'platform_commission_percent' => 0" in policy)
add('61 one free approved tier and no support advantage remain', "'approved_core_tier'" in policy and "'free'" in policy and "'support_affects_visibility'" in policy and 'false' in policy)
add('62 cure/income guarantees and deceptive conversion remain prohibited', 'cure_guarantee' in policy and 'guaranteed income' in future_policy)
add('63 emergency boundary remains educational and diversion-oriented', 'no_emergency_service' in policy and 'emergency' in future_policy.lower())
add('64 AI sensitive input is blocked before provider path', 'gcu_fifth_ai_sensitive_input_blocked' in fifth)
add('65 AI output passes multilingual dark-pattern guard', 'multilingual_dark_pattern_scan' in fifth and 'multilingual_guard_applied' in fifth)
add('66 AI suggestions can never auto-publish', 'gcu_future_ai_draft_cannot_publish' in r('14-global-clinic-usp-integration/includes/class-gcu-future-guards.php'))
add('67 FAQ intelligence can never auto-publish', 'gcu_future_faq_suggestion_cannot_publish' in r('14-global-clinic-usp-integration/includes/class-gcu-future-guards.php'))
add('68 public trust/change log is governed owner data', 'public_change_log' in future and 'change_log' in future)
add('69 Choose Safely guide remains educational', 'Choose Safely' in future_policy or 'choose safely' in future_policy.lower())
add('70 doctor readiness remains non-binding and verification-owned by File09/File00', 'binding' in future_policy and 'File 09 / File 00' in future_policy)
add('71 American English source plus complete Urdu/Arabic Future locale coverage remains', "'ur-PK'" in future_i18n and "'ar-SA'" in future_i18n and 'if ( ! $strings )' in future_i18n and 'Preparation estimate:' in future_i18n and 'American English canonical File 14 chrome' in trace)
add('72 RTL/LTR direction support remains', 'rtl' in css.lower() and ('rtl' in front.lower() or 'dir=' in front))
add('73 protected terminology/provenance remains', 'terminology_lock' in future_policy and 'provenance' in future_policy.lower())
add('74 Sabri Green remains exact primary token', '#087A4E' in loader and '#087A4E' in css and '#087A4E' in future_css)
add('75 accessibility interaction targets/focus controls remain', '44px' in css+future_css and 'focus-visible' in css+future_css)
add('76 reduced-motion forced-colors and 320px-class reflow remain', 'prefers-reduced-motion' in css+future_css and 'forced-colors' in future_css and ('320px' in css or '360px' in css))
add('77 400 percent zoom remains an external acceptance gate rather than false repository claim', '400%' in status or '400%' in release)
add('78 exact-head workflow retains PHP 7.4 and 8.3 matrix', "php: ['7.4','8.3']" in workflow)
add('79 deterministic package/SBOM plus executable-markup and secret gates remain', 'Deterministic double-build mismatch' in build and 'file-sha256-sbom-v1' in build and 'Inline executable markup detected' in quality and 'Potential embedded secret detected' in quality)
add('80 Live-First repository/staging/live truth separation remains explicit', 'No `Staging-Accepted`, `Live-Deployed` or `Operational` claim' in status and ('Staging' in release or 'staging' in release))

if len(checks)!=80:
    print(f'Sixth review definition error: {len(checks)} checks',file=sys.stderr);sys.exit(2)
failed=[]
for i,(label,ok) in enumerate(checks,1):
    print(f'Sixth Review {i:02d}: {"PASS" if ok else "FAIL"} — {label}')
    if not ok: failed.append((i,label))
if failed:
    print('\nFailed sixth-review gates:',file=sys.stderr)
    for i,label in failed: print(f'- Round {i:02d}: {label}',file=sys.stderr)
    sys.exit(1)
print('\nSixth independent eighty-pass repository review: PASS — 80/80 final-state gates satisfied')
