#!/usr/bin/env python3
"""Fifth independent 80-pass repository review gate for File 14 v1.4.3."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / "14-global-clinic-usp-integration"

def text(path):
    return path.read_text(encoding="utf-8")

main = text(P / "global-clinic-usp-integration.php")
fifth = text(P / "includes/class-gcu-fifth-review-hardening.php")
repo = text(P / "includes/class-gcu-repository.php")
install = text(P / "includes/class-gcu-install.php")
contracts = text(P / "includes/class-gcu-contracts.php")
privacy = text(P / "includes/class-gcu-privacy.php")
rest = text(P / "includes/class-gcu-rest.php")
frontend = text(P / "includes/class-gcu-frontend.php")
future = text(P / "includes/class-gcu-future-intelligence.php")
future_policy = text(P / "includes/class-gcu-future-policy.php")
future_i18n = text(P / "includes/class-gcu-future-i18n.php")
review80 = text(P / "includes/class-gcu-review80-hardening.php")
css = text(P / "assets/css/global-clinic-usp-integration.css")
future_css = text(P / "assets/css/gcu-future-intelligence.css")
js = text(P / "assets/js/global-clinic-usp-integration.js")
future_js = text(P / "assets/js/gcu-future-intelligence.js")
readme = text(P / "readme.txt")
root_readme = text(ROOT / "README.md")
status = text(ROOT / "STATUS.md")
trace = text(ROOT / "docs/REQUIREMENTS-TRACEABILITY.md")
build = text(ROOT / "scripts/build.py")
quality = text(ROOT / "scripts/quality.sh")
uninstall = text(P / "uninstall.php")

checks = []
def add(label, condition):
    checks.append((label, bool(condition)))

add("01 exact post-fourth-review baseline recorded", "b9045a4229d052103a5546477f664ac88b6ff034" in status)
add("02 base runtime schema truth gate", "GCU_Install::verify_schema()" in fifth)
add("03 Future runtime schema truth gate", "GCU_Future_Intelligence::verify_schema()" in fifth)
add("04 schema drift fail-closed", "return self::$schema_gate ? $pre_option : 0;" in fifth)
add("05 Founder approval for active/public Future governance", "future_public_governance" in fifth and "GCU_Capabilities::APPROVE_CLAIMS" in fifth)
add("06 AI sensitive input blocked before provider path", "gcu_fifth_ai_sensitive_input_blocked" in fifth and "question_contains_sensitive_data" in fifth)
add("07 AI multilingual output guard", "multilingual_dark_pattern_scan" in fifth and "multilingual_guard_applied" in fifth)
add("08 conflicting conversion event identity rejected", "gcu_conversion_event_identity_conflict" in fifth and "subject_hash" in fifth)
add("09 legacy hourly early-stop worker replaced", "remove_action( 'gcu_future_hourly_intelligence'" in fifth)
add("10 early-stop transaction boundary", "transactional_early_stop_guard" in fifth and "START TRANSACTION" in fifth and "COMMIT" in fifth)
add("11 early-stop mandatory audit rollback", "experiment_early_stopped" in fifth and "if ( false === $audit )" in fifth and "ROLLBACK" in fifth)
add("12 release documentation corrected to five ledgers", "The five repository review ledgers are:" in status)
add("13 plugin header/version parity", "Version: 1.4.3" in main and "GCU_VERSION', '1.4.3" in main)
add("14 stable tag parity", "Stable tag: 1.4.3" in readme)
add("15 root README version parity", "Software candidate: `1.4.3`" in root_readme)
add("16 Future plan identity", "SSH-F14-FUTURE-CTI-2026-v2.0" in main and "SSH-F14-FUTURE-CTI-2026-v2.0" in future_policy)
add("17 all 24 Future requirement IDs present", all(f"F14-FUT-{i:02d}" in future_policy for i in range(1, 25)))
add("18 canonical logical repository identity", "14-global-clinic-usp-and-conversion-integration" in main)
add("19 Sabri Green exact token", "#087A4E" in main and "#087A4E" in css and "#087A4E" in future_css)
add("20 File 20 sole shell ownership no fallback claim", "does not emit a local Back/Home shell fallback" in readme and "data-gcu-shell-fallback" not in frontend)
add("21 strict same-origin handoff", "strict_same_origin_url" in contracts and "strict_same_origin_url" in fifth)
add("22 deprecated host-only URL helper absent", "GCU_Policy::same_origin_url" not in "\n".join([contracts, frontend, rest, future, fifth]))
add("23 GPC respected", "global_privacy_control_requested" in privacy)
add("24 Save-Data respected", "low_bandwidth_requested" in privacy)
add("25 attribution limited to File14 acquisition routes", "is_file14_acquisition_route" in privacy)
add("26 WordPress privacy exporter", "wp_privacy_personal_data_exporters" in privacy)
add("27 WordPress privacy eraser", "wp_privacy_personal_data_erasers" in privacy)
add("28 JIT event token endpoint", "/event-token" in rest and "tokenEndpoint" in js)
add("29 single-use database token", "consumed_at IS NULL" in repo)
add("30 atomic database rate limit", "ON DUPLICATE KEY UPDATE counter=counter+1" in repo)
add("31 durable command store", "run_idempotent_command" in repo and "gcu_commands" in install)
add("32 outbox retry path", "dispatch_outbox" in repo and "next_attempt_at" in repo)
add("33 inbox replay/dedup path", "process_inbox" in repo and "payload_hash" in repo)
add("34 stale queue lock recovery", "INTERVAL 10 MINUTE" in repo)
add("35 audit append named lock", "'audit-chain'" in repo)
add("36 recent-tail audit verification", "recent_tail" in repo and "offset" in repo)
add("37 InnoDB base schema", "ENGINE=InnoDB" in install)
add("38 base required-column verification", "missing_columns" in install and "SHOW COLUMNS" in install)
add("39 Future required-column verification", "missing_columns" in future and "SHOW COLUMNS" in future)
add("40 rollback snapshot exists", "gcu_rollback_snapshot" in install and "snapshot_hash" in install)
add("41 rollback is governed/audited", "rollback" in install.lower() and "audit" in install.lower())
add("42 non-destructive uninstall default", "GCU_ALLOW_PURGE" in uninstall and "gcu_purge_on_uninstall" in uninstall)
add("43 File07 destination ownership", "'doctor_directory'" in contracts and "'owner'=>'File 07'" in contracts)
add("44 File08 destination ownership", "'clinic'" in contracts and "'owner'=>'File 08'" in contracts)
add("45 File09 destination ownership", "'doctor_onboarding'" in contracts and "'owner'=>'File 09'" in contracts)
add("46 File20 slot readiness fails closed", "sabri_shell_slot_ready_v1" in contracts and "return true===$ready" in contracts.replace(" ", ""))
add("47 public destination DTO minimized", "public_destination" in contracts and "reason" in contracts and "owner'=>'" not in contracts.split("public function public_destination($key)",1)[1].split("public function public_destination_health",1)[0])
add("48 owner readiness freshness bounded", "time()-DAY_IN_SECONDS" in contracts.replace(" ", ""))
add("49 campaign cannot alter authorization", "Campaign query values cannot alter authorization" in readme or "sanitize_campaign" in repo)
add("50 conversion stage allowlist", all(s in repo for s in ["impression","cta_selected","destination_loaded","application_started","booking_started"]))
add("51 owner stage/destination consistency", "gcu_stage_destination_mismatch" in repo)
add("52 stage-level small cohort suppression", "suppressed_stages" in repo and "MIN_COHORT" in review80)
add("53 Future friction small-cohort sanitizer", "sanitize_friction_payload" in review80)
add("54 FAQ sensitive aggregate guard", "question_contains_sensitive_data" in review80)
add("55 experiment meaningful guardrail validation", "guardrails_valid" in review80)
add("56 no sensitive experiment profiling", "health profiling" in future_policy and "sensitive_sampling" in future_policy)
add("57 experiment end date bounded", "90*DAY_IN_SECONDS" in repo.replace(" ", ""))
add("58 claim freshness sentinel", "claim_freshness_sentinel" in future)
add("59 zero-commission parity sentinel", "parity_status" in future and "zero_commission" in future_policy)
add("60 public trust only current claims", "public_claims" in repo and "review_due_at>UTC_TIMESTAMP()" in repo.replace(" ", ""))
add("61 public change log is owner-governed data", "public_change_log" in future and "change_log" in future)
add("62 readiness self-check non-binding", "'binding' => false" in future_policy and "File 09 / File 00" in future_policy)
add("63 patient guide emergency limitation", "life-threatening" in future_policy and "emergency care" in future_policy)
add("64 AI never auto-publishes", "auto_publish" in future and "auto-publishes" in future_policy)
add("65 Future locale terminology lock", all(x in future_policy for x in ["en-US","ur-PK","ar-SA","terminology_lock"]))
add("66 complete Urdu Future UI set", "'ur-PK'" in future_i18n and "Choose your next step" in future_i18n and "Send report" in future_i18n)
add("67 complete Arabic Future UI set", "'ar-SA'" in future_i18n and "Preparation estimate:" in future_i18n)
add("68 RTL direction support", "dir=" in frontend or "rtl" in frontend.lower())
add("69 reduced motion support", "prefers-reduced-motion" in css and "prefers-reduced-motion" in future_css)
add("70 forced-colors support", "forced-colors" in future_css)
add("71 320px-class reflow control", "360px" in css or "320px" in css)
add("72 no inline executable markup", not re.search(r"onclick=|onload=|onerror=|javascript:", "\n".join([frontend, future, readme]), re.I))
add("73 no event token embedded in HTML", "data-gcu-event-token" not in "\n".join([frontend, future, readme]))
add("74 deterministic double build", "Deterministic double-build mismatch" in build and "build-a.zip" in build and "build-b.zip" in build)
add("75 archive path and CRC validation", "Unsafe archive path" in build and "testzip" in build)
add("76 file-level SBOM", "file-sha256-sbom-v1" in build and "package_sha256" in build)
add("77 PHP 7.4/8.3 workflow intent", "PHP 7.4" in readme and "PHP 8.3" in trace)
add("78 fifth regression is in quality gate", "fifth-review-regression-tests.php" in quality)
add("79 fifth 80-pass gate is in quality gate", "review80-fifth.py" in quality)
add("80 live/staging/repository truth remains separated", "No `Staging-Accepted`, `Live-Deployed` or `Operational` claim" in status)

if len(checks) != 80:
    print(f"Fifth 80-pass gate definition error: expected 80 checks, got {len(checks)}", file=sys.stderr)
    sys.exit(2)

failed = [(i + 1, label) for i, (label, ok) in enumerate(checks) if not ok]
for i, (label, ok) in enumerate(checks, 1):
    print(f"{i:02d} {'PASS' if ok else 'FAIL'} — {label}")

if failed:
    print("Fifth 80-pass gate failed:", file=sys.stderr)
    for i, label in failed:
        print(f"- Round {i:02d}: {label}", file=sys.stderr)
    sys.exit(1)

print("Fifth independent eighty-pass gate: PASS — 80/80")
