<?php

defined( 'ABSPATH' ) || exit;

final class GCU_Install {
	const LOCK_OPTION='gcu_install_lock'; const VERSION_OPTION='gcu_version'; const SCHEMA_OPTION='gcu_schema_version'; const SNAPSHOT_OPTION='gcu_rollback_snapshot'; const MIGRATION_LOG='gcu_migration_log'; const UPGRADE_ERROR='gcu_upgrade_error'; const SNAPSHOT_MAX=1500000; const SNAPSHOT_ROW_MAX=1000; private static $db_lock=false;
	public static function cron_schedules($s){if(!isset($s['gcu_five_minutes'])){$s['gcu_five_minutes']=array('interval'=>300,'display'=>__('Every five minutes (File 14)','global-clinic-usp-integration'));}return $s;}
	public static function activate(){$r=self::install_or_upgrade(true);if(is_wp_error($r)){update_option(self::UPGRADE_ERROR,self::safe_error_record($r),false);update_option('gcu_enabled',0,false);wp_die(esc_html($r->get_error_message()));}$future=self::ensure_future_schema(true);if(is_wp_error($future)){update_option(self::UPGRADE_ERROR,self::safe_error_record($future),false);update_option('gcu_enabled',0,false);wp_die(esc_html($future->get_error_message()));}}
	public static function deactivate(){foreach(array('gcu_daily_governance_check','gcu_process_outbox','gcu_process_inbox','gcu_lifecycle_cleanup','gcu_future_daily_governance','gcu_future_hourly_intelligence')as$h){wp_clear_scheduled_hook($h);}flush_rewrite_rules();}
	public static function safe_repair(){
		$result=self::install_or_upgrade(false);
		if(is_wp_error($result)){return $result;}
		return self::ensure_future_schema(true);
	}
	public static function maybe_upgrade(){if(GCU_VERSION===(string)get_option(self::VERSION_OPTION,'')&&GCU_SCHEMA_VERSION===(int)get_option(self::SCHEMA_OPTION,0)){$future=self::ensure_future_schema();if(is_wp_error($future)){update_option(self::UPGRADE_ERROR,self::safe_error_record($future),false);return$future;}return true;}$r=self::install_or_upgrade(false);if(is_wp_error($r)){update_option(self::UPGRADE_ERROR,self::safe_error_record($r),false);update_option('gcu_enabled',0,false);return$r;}$future=self::ensure_future_schema(true);if(is_wp_error($future)){update_option(self::UPGRADE_ERROR,self::safe_error_record($future),false);return$future;}return true;}
	private static function ensure_future_schema($force_verify=false){if(!class_exists('GCU_Future_Intelligence')){return true;}$r=GCU_Future_Intelligence::ensure_schema($force_verify);if(is_wp_error($r)){update_option(GCU_Future_Intelligence::SAFE_MODE_OPTION,1,false);GCU_Observability::log('error','future_schema_upgrade_deferred',array('code'=>$r->get_error_code()));}return$r;}
	public static function ready_for_runtime(){if(self::install_lock_active()){return new WP_Error('gcu_install_in_progress',__('File 14 install, upgrade or recovery is in progress.','global-clinic-usp-integration'),array('status'=>503));}if(!get_option('gcu_enabled',1)){return new WP_Error('gcu_safe_mode',__('File 14 is in safe mode.','global-clinic-usp-integration'),array('status'=>503));}if(GCU_VERSION!==(string)get_option(self::VERSION_OPTION,'')||GCU_SCHEMA_VERSION!==(int)get_option(self::SCHEMA_OPTION,0)){return new WP_Error('gcu_upgrade_pending',__('File 14 requires a verified schema upgrade before runtime can continue.','global-clinic-usp-integration'),array('status'=>503));}return true;}public static function ready_for_mutation(){return self::ready_for_runtime();}
	private static function install_or_upgrade($activation){if(!self::acquire_lock()){return new WP_Error('gcu_install_locked',__('Global Clinic USP installation or upgrade is already running. Please retry shortly.','global-clinic-usp-integration'));}try{$keys=GCU_Integrity::ensure_keys();if(is_wp_error($keys)){return $keys;}$snap=self::capture_snapshot(true);if(is_wp_error($snap)){return $snap;}$schema=self::schema();if(is_wp_error($schema)){return $schema;}GCU_Capabilities::install();$seed=self::seed_governed_content();if(is_wp_error($seed)){return $seed;}$migration=self::migrate_legacy();if(is_wp_error($migration)){return $migration;}$integrity=GCU_Integrity::migrate_legacy_hashes();if(is_wp_error($integrity)){return $integrity;}$scheduled=self::schedule();if(is_wp_error($scheduled)){return$scheduled;}update_option(self::VERSION_OPTION,GCU_VERSION,false);update_option(self::SCHEMA_OPTION,GCU_SCHEMA_VERSION,false);delete_option(self::UPGRADE_ERROR);if($activation){update_option('gcu_enabled',1,false);}flush_rewrite_rules();return true;}finally{self::release_lock();}}
	public static function schema(){global$wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();$t=self::tables();$e="ENGINE=InnoDB $c";$sql=array();
$sql[]="CREATE TABLE {$t['claims']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,public_id char(36) NOT NULL,claim_key varchar(191) NOT NULL,claim_text text NOT NULL,basis text NOT NULL,owner_name varchar(191) NOT NULL,source_uri text NULL,status varchar(32) NOT NULL DEFAULT 'active',effective_at datetime NOT NULL,review_due_at datetime NULL,expires_at datetime NULL,is_public tinyint(1) NOT NULL DEFAULT 0,row_version bigint(20) unsigned NOT NULL DEFAULT 1,created_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY public_id (public_id),UNIQUE KEY claim_key (claim_key),KEY status_review (status,review_due_at)) $e;";
$sql[]="CREATE TABLE {$t['claim_history']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,claim_key varchar(191) NOT NULL,row_version bigint(20) unsigned NOT NULL,status varchar(32) NOT NULL,claim_hash char(64) NOT NULL,reason varchar(191) NULL,snapshot longtext NOT NULL,actor_id bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY claim_version (claim_key,row_version),KEY claim_time (claim_key,created_at)) $e;";
$sql[]="CREATE TABLE {$t['blocks']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,public_id char(36) NOT NULL,block_key varchar(191) NOT NULL,audience varchar(32) NOT NULL DEFAULT 'all',block_type varchar(32) NOT NULL,slot_key varchar(191) NOT NULL,locale varchar(32) NOT NULL DEFAULT 'en-US',title text NOT NULL,body longtext NOT NULL,cta_label text NULL,cta_destination varchar(64) NULL,claim_keys longtext NULL,status varchar(32) NOT NULL DEFAULT 'draft',content_version bigint(20) unsigned NOT NULL DEFAULT 1,row_version bigint(20) unsigned NOT NULL DEFAULT 1,approved_by bigint(20) unsigned NOT NULL DEFAULT 0,approved_at datetime NULL,review_due_at datetime NULL,created_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY public_id (public_id),UNIQUE KEY block_locale_version (block_key,locale,content_version),KEY active_slot (status,slot_key,audience,locale)) $e;";
$sql[]="CREATE TABLE {$t['placements']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,public_id char(36) NOT NULL,placement_key varchar(191) NOT NULL,block_key varchar(191) NOT NULL,route_key varchar(191) NOT NULL,slot_key varchar(191) NOT NULL,audience varchar(32) NOT NULL DEFAULT 'all',priority int(11) NOT NULL DEFAULT 100,status varchar(32) NOT NULL DEFAULT 'planned',starts_at datetime NULL,ends_at datetime NULL,row_version bigint(20) unsigned NOT NULL DEFAULT 1,created_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY public_id (public_id),UNIQUE KEY placement_key (placement_key),KEY active_route_slot (status,route_key,slot_key,audience,priority)) $e;";
$sql[]="CREATE TABLE {$t['experiments']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,public_id char(36) NOT NULL,experiment_key varchar(191) NOT NULL,hypothesis text NOT NULL,variants longtext NOT NULL,audience varchar(32) NOT NULL DEFAULT 'all',guardrails longtext NOT NULL,success_metric varchar(191) NOT NULL,sample_policy text NOT NULL,privacy_policy text NOT NULL,status varchar(32) NOT NULL DEFAULT 'proposed',starts_at datetime NULL,ends_at datetime NULL,row_version bigint(20) unsigned NOT NULL DEFAULT 1,approved_by bigint(20) unsigned NOT NULL DEFAULT 0,created_by bigint(20) unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY public_id (public_id),UNIQUE KEY experiment_key (experiment_key),KEY status_window (status,starts_at,ends_at)) $e;";
$sql[]="CREATE TABLE {$t['events']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,event_id char(36) NOT NULL,event_type varchar(100) NOT NULL,event_version smallint(5) unsigned NOT NULL DEFAULT 1,funnel_stage varchar(64) NOT NULL,destination_key varchar(64) NULL,subject_hash char(64) NULL,source_value varchar(100) NULL,medium_value varchar(100) NULL,campaign_value varchar(100) NULL,ref_value varchar(100) NULL,consent_state varchar(16) NOT NULL DEFAULT 'denied',occurred_at datetime NOT NULL,created_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY event_id (event_id),KEY funnel_time (funnel_stage,occurred_at),KEY campaign_time (campaign_value,occurred_at),KEY subject_time (subject_hash,occurred_at)) $e;";
$sql[]="CREATE TABLE {$t['audit']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,trace_id varchar(64) NOT NULL,actor_id bigint(20) unsigned NOT NULL DEFAULT 0,action_name varchar(100) NOT NULL,object_type varchar(64) NOT NULL,object_id varchar(191) NOT NULL,purpose varchar(100) NOT NULL,reason text NULL,before_hash char(64) NULL,after_hash char(64) NULL,previous_hash char(64) NOT NULL,row_hash char(64) NOT NULL,created_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY row_hash (row_hash),KEY trace_id (trace_id),KEY object_lookup (object_type,object_id),KEY actor_time (actor_id,created_at)) $e;";
$sql[]="CREATE TABLE {$t['outbox']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,event_id char(36) NOT NULL,event_name varchar(100) NOT NULL,event_version smallint(5) unsigned NOT NULL DEFAULT 1,payload longtext NOT NULL,status varchar(24) NOT NULL DEFAULT 'pending',attempts smallint(5) unsigned NOT NULL DEFAULT 0,locked_at datetime NULL,next_attempt_at datetime NULL,last_error_code varchar(100) NULL,created_at datetime NOT NULL,dispatched_at datetime NULL,PRIMARY KEY (id),UNIQUE KEY event_id (event_id),KEY dispatch_queue (status,next_attempt_at,id)) $e;";
$sql[]="CREATE TABLE {$t['inbox']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,event_id char(36) NOT NULL,event_name varchar(100) NOT NULL,payload_hash char(64) NOT NULL,payload longtext NOT NULL,status varchar(24) NOT NULL DEFAULT 'pending',attempts smallint(5) unsigned NOT NULL DEFAULT 0,locked_at datetime NULL,next_attempt_at datetime NULL,last_error_code varchar(100) NULL,created_at datetime NOT NULL,processed_at datetime NULL,PRIMARY KEY (id),UNIQUE KEY event_id (event_id),KEY inbox_queue (status,next_attempt_at,id),KEY event_name (event_name)) $e;";
$sql[]="CREATE TABLE {$t['event_tokens']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,token_id char(36) NOT NULL,token_hash char(64) NOT NULL,purpose varchar(32) NOT NULL,expires_at datetime NOT NULL,consumed_at datetime NULL,created_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY token_id (token_id),UNIQUE KEY token_hash (token_hash),KEY usable_token (purpose,expires_at,consumed_at)) $e;";
$sql[]="CREATE TABLE {$t['rate_limits']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,bucket_key varchar(191) NOT NULL,counter int(10) unsigned NOT NULL DEFAULT 0,expires_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY bucket_key (bucket_key),KEY expiry (expires_at)) $e;";
$sql[]="CREATE TABLE {$t['commands']} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,command_key varchar(191) NOT NULL,command_name varchar(100) NOT NULL,request_hash char(64) NOT NULL DEFAULT '',actor_id bigint(20) unsigned NOT NULL DEFAULT 0,status varchar(24) NOT NULL DEFAULT 'processing',attempts smallint(5) unsigned NOT NULL DEFAULT 1,result_json longtext NULL,error_code varchar(100) NULL,locked_at datetime NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY (id),UNIQUE KEY command_key (command_key),KEY status_lock (status,locked_at)) $e;";
foreach($sql as$s){dbDelta($s);}return self::verify_schema();}
	public static function tables(){global$wpdb;return array('claims'=>$wpdb->prefix.'gcu_claims','claim_history'=>$wpdb->prefix.'gcu_claim_history','blocks'=>$wpdb->prefix.'gcu_content_blocks','placements'=>$wpdb->prefix.'gcu_placements','experiments'=>$wpdb->prefix.'gcu_experiments','events'=>$wpdb->prefix.'gcu_conversion_events','audit'=>$wpdb->prefix.'gcu_audit_log','outbox'=>$wpdb->prefix.'gcu_event_outbox','inbox'=>$wpdb->prefix.'gcu_event_inbox','event_tokens'=>$wpdb->prefix.'gcu_event_tokens','rate_limits'=>$wpdb->prefix.'gcu_rate_limits','commands'=>$wpdb->prefix.'gcu_commands');}
	public static function verify_schema(){global$wpdb;$m=array();$w=array();$mc=array();$required=array(
'claims'=>array('public_id','claim_key','claim_text','status','review_due_at','row_version'),
'claim_history'=>array('claim_key','row_version','status','claim_hash','snapshot'),
'blocks'=>array('public_id','block_key','locale','status','content_version','claim_keys','row_version','review_due_at'),
'placements'=>array('public_id','placement_key','block_key','slot_key','status','row_version'),
'experiments'=>array('public_id','experiment_key','status','guardrails','row_version','ends_at'),
'events'=>array('event_id','subject_hash','funnel_stage','destination_key','occurred_at'),
'audit'=>array('trace_id','row_hash','previous_hash','created_at'),
'outbox'=>array('event_id','status','attempts','locked_at','next_attempt_at'),
'inbox'=>array('event_id','status','attempts','locked_at','next_attempt_at'),
'event_tokens'=>array('token_hash','purpose','expires_at','consumed_at'),
'rate_limits'=>array('bucket_key','counter','expires_at'),
'commands'=>array('command_key','command_name','request_hash','status','attempts','locked_at','result_json'));
foreach(self::tables()as$k=>$table){$f=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($table)));if($table!==$f){$m[]=$k;continue;}$s=$wpdb->get_row($wpdb->prepare('SHOW TABLE STATUS LIKE %s',$wpdb->esc_like($table)),ARRAY_A);$e=is_array($s)&&isset($s['Engine'])?strtolower((string)$s['Engine']):'';if('innodb'!==$e){$w[$k]=$e?$e:'unknown';}$cols=$wpdb->get_col("SHOW COLUMNS FROM `$table`",0);$missing_cols=array_values(array_diff(isset($required[$k])?$required[$k]:array(),is_array($cols)?$cols:array()));if($missing_cols){$mc[$k]=$missing_cols;}}
return($m||$w||$mc)?new WP_Error('gcu_schema_verification_failed',__('File 14 database schema could not be verified safely.','global-clinic-usp-integration'),array('missing'=>$m,'non_innodb'=>$w,'missing_columns'=>$mc)):true;}
	public static function seed_governed_content(){global$wpdb;$t=self::tables();$now=current_time('mysql',true);foreach(GCU_Policy::canonical_claims()as$key=>$claim){$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t['claims']} WHERE claim_key=%s",$key));if($exists){continue;}$r=array('public_id'=>wp_generate_uuid4(),'claim_key'=>$key,'claim_text'=>$claim['text'],'basis'=>$claim['basis'],'owner_name'=>$claim['owner'],'source_uri'=>GCU_PLAN_VERSION,'status'=>'active','effective_at'=>gmdate('Y-m-d H:i:s',$claim['effective']),'review_due_at'=>gmdate('Y-m-d H:i:s',$claim['review_due']),'is_public'=>empty($claim['public'])?0:1,'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now);if(false===$wpdb->insert($t['claims'],$r)){return new WP_Error('gcu_seed_claim_failed',__('A canonical claim could not be seeded safely.','global-clinic-usp-integration'));}$h=array('claim_key'=>$key,'row_version'=>1,'status'=>'active','claim_hash'=>hash('sha256',wp_json_encode($r)),'reason'=>'canonical_seed','snapshot'=>wp_json_encode($r),'actor_id'=>get_current_user_id(),'created_at'=>$now);if(false===$wpdb->insert($t['claim_history'],$h)){return new WP_Error('gcu_seed_claim_history_failed',__('Canonical claim history could not be seeded safely.','global-clinic-usp-integration'));}}
foreach(GCU_Policy::canonical_block_sets()as$locale=>$blocks){foreach($blocks as$key=>$b){$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t['blocks']} WHERE block_key=%s AND locale=%s AND content_version=1",$key,$locale));if($exists){continue;}$r=array('public_id'=>wp_generate_uuid4(),'block_key'=>$key,'audience'=>$b['audience'],'block_type'=>$b['type'],'slot_key'=>$b['slot'],'locale'=>$locale,'title'=>$b['title'],'body'=>$b['body'],'cta_label'=>$b['cta_label'],'cta_destination'=>$b['destination'],'claim_keys'=>wp_json_encode($b['claim_keys']),'status'=>'active','content_version'=>1,'approved_by'=>get_current_user_id(),'approved_at'=>$now,'review_due_at'=>gmdate('Y-m-d H:i:s',time()+(GCU_Policy::COPY_REVIEW_DAYS*DAY_IN_SECONDS)),'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now);if(false===$wpdb->insert($t['blocks'],$r)){return new WP_Error('gcu_seed_block_failed',__('A canonical content block could not be seeded safely.','global-clinic-usp-integration'));}}}
$p=array('global_clinic_patient'=>array('patient_hero','global_clinic','global_clinic_primary','patient',10),'global_clinic_doctor'=>array('doctor_hero','global_clinic','global_clinic_primary','doctor',20),'global_clinic_trust'=>array('trust','global_clinic','global_clinic_trust','all',30),'global_clinic_steps'=>array('how_it_works','global_clinic','global_clinic_steps','all',40),'global_clinic_faq_approval'=>array('faq_approval','global_clinic','global_clinic_faq','all',50),'global_clinic_faq_commission'=>array('faq_commission','global_clinic','global_clinic_faq','all',51),'global_clinic_faq_clinical'=>array('faq_clinical','global_clinic','global_clinic_faq','all',52),'global_clinic_faq_outcome'=>array('faq_outcome','global_clinic','global_clinic_faq','all',53));foreach($p as$key=>$v){$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t['placements']} WHERE placement_key=%s",$key));if($exists){continue;}$r=array('public_id'=>wp_generate_uuid4(),'placement_key'=>$key,'block_key'=>$v[0],'route_key'=>$v[1],'slot_key'=>$v[2],'audience'=>$v[3],'priority'=>$v[4],'status'=>'active','created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now);if(false===$wpdb->insert($t['placements'],$r)){return new WP_Error('gcu_seed_placement_failed',__('A canonical placement could not be seeded safely.','global-clinic-usp-integration'));}}return true;}
	public static function migrate_legacy(){if(get_option('gcu_legacy_migrated',false)){return true;}$l=array('sgc_version'=>get_option('sgc_version',null),'sgc_schema_version'=>get_option('sgc_schema_version',null),'sgc_placements'=>get_option('sgc_placements',null),'sgc_page_map'=>get_option('sgc_page_map',null));$d=array_filter($l,static function($v){return null!==$v;});update_option(self::MIGRATION_LOG,array('detected'=>!empty($d),'legacy_snapshot'=>$d,'action'=>'read-only inventory; no legacy page, option or companion record deleted or overwritten','migrated_at'=>time()),false);update_option('gcu_legacy_migrated',1,false);return true;}
	public static function capture_snapshot($force=false){if(!$force&&get_option(self::SNAPSHOT_OPTION,false)){return true;}global$wpdb;$names=array(self::VERSION_OPTION,self::SCHEMA_OPTION,'gcu_enabled','gcu_settings','gcu_legacy_migrated',self::MIGRATION_LOG);if(class_exists('GCU_Future_Intelligence')){$names[]=GCU_Future_Intelligence::SCHEMA_OPTION;$names[]=GCU_Future_Intelligence::SAFE_MODE_OPTION;}$s=array('captured_at'=>time(),'options'=>array(),'tables'=>array());foreach($names as$n){$sent='__gcu_missing__'.wp_generate_uuid4();$v=get_option($n,$sent);$s['options'][$n]=array('exists'=>$sent!==$v,'value'=>$sent!==$v?$v:null);}$maps=array();$base=self::tables();foreach(array('claims','claim_history','blocks','placements','experiments')as$k){$maps[$k]=$base[$k];}if(class_exists('GCU_Future_Intelligence')){$ft=GCU_Future_Intelligence::tables();$maps['future_records']=$ft['records'];$maps['future_reports']=$ft['reports'];}foreach($maps as$k=>$table){$wpdb->last_error='';$exists=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($table)));if(''!==(string)$wpdb->last_error){return new WP_Error('gcu_snapshot_table_probe_failed',__('File 14 rollback snapshot could not verify an owner table.','global-clinic-usp-integration'));}if($table!==$exists){$s['tables'][$k]=array();continue;}$wpdb->last_error='';$count_raw=$wpdb->get_var("SELECT COUNT(*) FROM `$table`");if(''!==(string)$wpdb->last_error){return new WP_Error('gcu_snapshot_count_failed',__('File 14 rollback snapshot could not verify owner row counts.','global-clinic-usp-integration'));}$count=(int)$count_raw;if($count>self::SNAPSHOT_ROW_MAX){return new WP_Error('gcu_snapshot_too_large',__('File 14 owner data exceeds the bounded rollback snapshot limit.','global-clinic-usp-integration'));}$wpdb->last_error='';$rows=$wpdb->get_results("SELECT * FROM `$table` ORDER BY id ASC",ARRAY_A);if(''!==(string)$wpdb->last_error||!is_array($rows)){return new WP_Error('gcu_snapshot_read_failed',__('File 14 rollback snapshot could not read owner data.','global-clinic-usp-integration'));}$s['tables'][$k]=$rows;}$enc=wp_json_encode($s);if(false===$enc||strlen($enc)>self::SNAPSHOT_MAX){return new WP_Error('gcu_snapshot_size_failed',__('File 14 rollback snapshot exceeds its safe storage bound.','global-clinic-usp-integration'));}$s['snapshot_hash']=hash('sha256',$enc);update_option(self::SNAPSHOT_OPTION,$s,false);$stored=get_option(self::SNAPSHOT_OPTION,array());if(!is_array($stored)||empty($stored['snapshot_hash'])||!hash_equals((string)$s['snapshot_hash'],(string)$stored['snapshot_hash'])){return new WP_Error('gcu_snapshot_persist_failed',__('File 14 rollback snapshot could not be persisted and verified safely.','global-clinic-usp-integration'));}return true;}
	public static function rollback_options(){return self::rollback_snapshot();}
	public static function rollback_snapshot(){global$wpdb;if(!self::acquire_lock()){return new WP_Error('gcu_rollback_locked',__('A File 14 install, upgrade or recovery operation is already running.','global-clinic-usp-integration'));}try{$s=get_option(self::SNAPSHOT_OPTION,array());if(empty($s['snapshot_hash'])||!isset($s['options'],$s['tables'])){return new WP_Error('gcu_no_snapshot',__('No verified rollback snapshot is available.','global-clinic-usp-integration'));}$copy=$s;$hash=(string)$copy['snapshot_hash'];unset($copy['snapshot_hash']);$enc=wp_json_encode($copy);if(false===$enc||!hash_equals($hash,hash('sha256',$enc))){return new WP_Error('gcu_snapshot_integrity_failed',__('The File 14 rollback snapshot failed integrity verification.','global-clinic-usp-integration'));}$v=self::verify_schema();if(is_wp_error($v)){return $v;}if(isset($s['tables']['future_records'])||isset($s['tables']['future_reports'])){$fv=class_exists('GCU_Future_Intelligence')?GCU_Future_Intelligence::verify_schema():new WP_Error('gcu_future_schema_unavailable',__('Future schema verifier is unavailable.','global-clinic-usp-integration'));if(is_wp_error($fv)){return $fv;}}$base=self::tables();$maps=array('claim_history'=>$base['claim_history'],'claims'=>$base['claims'],'blocks'=>$base['blocks'],'placements'=>$base['placements'],'experiments'=>$base['experiments']);if(class_exists('GCU_Future_Intelligence')){$ft=GCU_Future_Intelligence::tables();$maps['future_records']=$ft['records'];$maps['future_reports']=$ft['reports'];}if(false===$wpdb->query('START TRANSACTION')){return new WP_Error('gcu_rollback_transaction_failed',__('Rollback transaction could not start.','global-clinic-usp-integration'));}try{$captured_at=gmdate('Y-m-d H:i:s',isset($s['captured_at'])?(int)$s['captured_at']:0);foreach($maps as$k=>$table){if(!array_key_exists($k,$s['tables'])){continue;}foreach(is_array($s['tables'][$k])?$s['tables'][$k]:array()as$row){if(!is_array($row)||empty($row['id'])){throw new RuntimeException('invalid-'.$k);}$current=$wpdb->get_row($wpdb->prepare("SELECT * FROM `$table` WHERE id=%d",(int)$row['id']),ARRAY_A);if($current){$changed_at=!empty($current['updated_at'])?$current['updated_at']:(isset($current['created_at'])?$current['created_at']:'');if($captured_at&&$changed_at&&strtotime($changed_at.' UTC')>strtotime($captured_at.' UTC')){continue;}$ok=$wpdb->replace($table,$row);if(false===$ok){throw new RuntimeException('replace-'.$k);}}else{$ok=$wpdb->insert($table,$row);if(false===$ok){throw new RuntimeException('insert-'.$k);}}}}if(false===$wpdb->query('COMMIT')){throw new RuntimeException('commit');}}catch(Exception$e){$wpdb->query('ROLLBACK');return new WP_Error('gcu_rollback_write_failed',__('File 14 rollback could not be completed atomically.','global-clinic-usp-integration'));}foreach($s['options']as$n=>$entry){if(empty($entry['exists'])){delete_option($n);}else{update_option($n,$entry['value'],false);}}return true;}finally{self::release_lock();}}
	public static function schedule(){foreach(array(array('gcu_daily_governance_check',time()+HOUR_IN_SECONDS,'daily'),array('gcu_process_outbox',time()+300,'gcu_five_minutes'),array('gcu_process_inbox',time()+330,'gcu_five_minutes'),array('gcu_lifecycle_cleanup',time()+HOUR_IN_SECONDS,'hourly'))as$job){if(wp_next_scheduled($job[0])){continue;}$r=wp_schedule_event($job[1],$job[2],$job[0],array(),true);if(is_wp_error($r)||false===$r){$code=is_wp_error($r)?$r->get_error_code():'schedule_failed';GCU_Observability::log('error','cron_schedule_failed',array('hook'=>$job[0],'code'=>$code));return new WP_Error('gcu_cron_schedule_failed',__('File 14 could not schedule a required governance or delivery job.','global-clinic-usp-integration'),array('hook'=>$job[0],'code'=>$code));}}return true;}
	private static function install_lock_active(){global$wpdb;$state=get_option(self::LOCK_OPTION,false);if(!$state){return false;}$at=is_array($state)&&!empty($state['acquired_at'])?(int)$state['acquired_at']:0;if($at&&$at>time()-600){return true;}$name=substr($wpdb->prefix.'gcu-install-upgrade',0,64);$wpdb->last_error='';$used=$wpdb->get_var($wpdb->prepare('SELECT IS_USED_LOCK(%s)',$name));if(''!==(string)$wpdb->last_error){GCU_Observability::log('error','install_lock_probe_failed',array('age'=>$at?max(0,time()-$at):null));return true;}if(null===$used||false===$used||0===(int)$used){delete_option(self::LOCK_OPTION);GCU_Observability::log('warning','stale_install_lock_recovered',array('age'=>$at?max(0,time()-$at):null));return false;}return true;}
	private static function acquire_lock(){global$wpdb;$name=substr($wpdb->prefix.'gcu-install-upgrade',0,64);$locked=(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s, 1)',$name));if(1!==$locked){return false;}self::$db_lock=$name;update_option(self::LOCK_OPTION,array('acquired_at'=>time(),'request'=>GCU_Policy::trace_id()),false);return true;}
	private static function release_lock(){global$wpdb;if(self::$db_lock){$wpdb->get_var($wpdb->prepare('SELECT RELEASE_LOCK(%s)',self::$db_lock));self::$db_lock=false;}delete_option(self::LOCK_OPTION);}
	private static function safe_error_record(WP_Error$e){return array('code'=>sanitize_key($e->get_error_code()),'occurred_at'=>time(),'version'=>GCU_VERSION,'schema'=>GCU_SCHEMA_VERSION);}
}
