<?php

defined('ABSPATH')||exit;
final class GCU_REST{
const NAMESPACE='gcu/v1',IDEMPOTENCY_HEADER='X-GCU-Idempotency-Key';
public function hooks(){add_action('rest_api_init',array($this,'register_routes'));}
public function register_routes(){register_rest_route(self::NAMESPACE,'/blocks',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'blocks'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/destinations',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'destinations'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/event-token',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'event_token'),'permission_callback'=>array($this,'can_issue_event_token')));register_rest_route(self::NAMESPACE,'/events',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'event'),'permission_callback'=>array($this,'verify_event_token')));register_rest_route(self::NAMESPACE,'/content',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'create_content'),'permission_callback'=>array($this,'can_manage_content')));register_rest_route(self::NAMESPACE,'/placements',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'create_placement'),'permission_callback'=>array($this,'can_manage_placements')));register_rest_route(self::NAMESPACE,'/experiments',array('methods'=>WP_REST_Server::CREATABLE,'callback'=>array($this,'create_experiment'),'permission_callback'=>array($this,'can_manage_experiments')));register_rest_route(self::NAMESPACE,'/claims/(?P<claim_key>[a-z0-9_\-]+)/withdraw',array('methods'=>WP_REST_Server::EDITABLE,'callback'=>array($this,'withdraw_claim'),'permission_callback'=>array($this,'can_approve_claims')));register_rest_route(self::NAMESPACE,'/workflow/(?P<machine>copy|placement|experiment)/(?P<public_id>[a-f0-9\-]{36})',array('methods'=>WP_REST_Server::EDITABLE,'callback'=>array($this,'transition'),'permission_callback'=>array($this,'can_manage_workflow')));register_rest_route(self::NAMESPACE,'/analytics/funnel',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'funnel'),'permission_callback'=>array($this,'can_view_analytics')));register_rest_route(self::NAMESPACE,'/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array($this,'health'),'permission_callback'=>array($this,'can_system_check')));}
public function blocks(WP_REST_Request$r){if(!get_option('gcu_enabled',1)){return new WP_Error('gcu_safe_mode',__('File 14 is temporarily unavailable.','global-clinic-usp-integration'),array('status'=>503));}$rows=GCU_Plugin::instance()->repository()->active_blocks(sanitize_key($r->get_param('slot')),GCU_Policy::sanitize_audience($r->get_param('audience')?:'all'),GCU_Policy::sanitize_locale($r->get_param('locale')?:GCU_Plugin::instance()->frontend()->current_locale()));return$this->cache_public_response(new WP_REST_Response(array('items'=>$rows,'count'=>count($rows),'version'=>1),200),300);}
public function destinations(){return$this->cache_public_response(new WP_REST_Response(array('items'=>GCU_Plugin::instance()->contracts()->all_destination_health(),'version'=>1),200),60);}
public function event_token(){$x=GCU_Plugin::instance()->repository()->issue_event_token('measurement');return is_wp_error($x)?$x:$this->no_store(new WP_REST_Response($x,201));}
public function event(WP_REST_Request$r){$d=$r->get_json_params();$d=is_array($d)?$d:array();$d['campaign']=GCU_Plugin::instance()->privacy()->current_campaign();$x=GCU_Plugin::instance()->repository()->record_event($d);return is_wp_error($x)?$x:$this->no_store(new WP_REST_Response($x,201));}
public function create_content(WP_REST_Request$r){$d=$r->get_json_params();$k=$this->required_idempotency_key($r);if(is_wp_error($k)){return$k;}$x=GCU_Plugin::instance()->repository()->run_idempotent_command('create_content',$k,function()use($d){return GCU_Plugin::instance()->repository()->create_content_draft(is_array($d)?$d:array(),get_current_user_id());});return is_wp_error($x)?$x:$this->no_store(new WP_REST_Response($x,201));}
public function create_placement(WP_REST_Request$r){$d=$r->get_json_params();$k=$this->required_idempotency_key($r);if(is_wp_error($k)){return$k;}$x=GCU_Plugin::instance()->repository()->run_idempotent_command('create_placement',$k,function()use($d){return GCU_Plugin::instance()->repository()->create_placement(is_array($d)?$d:array());});return is_wp_error($x)?$x:$this->no_store(new WP_REST_Response($x,201));}
public function create_experiment(WP_REST_Request$r){$d=$r->get_json_params();$k=$this->required_idempotency_key($r);if(is_wp_error($k)){return$k;}$x=GCU_Plugin::instance()->repository()->run_idempotent_command('create_experiment',$k,function()use($d){return GCU_Plugin::instance()->repository()->create_experiment(is_array($d)?$d:array());});return is_wp_error($x)?$x:$this->no_store(new WP_REST_Response($x,201));}
public function withdraw_claim(WP_REST_Request$r){$k=$this->required_idempotency_key($r);if(is_wp_error($k)){return$k;}$x=GCU_Plugin::instance()->repository()->run_idempotent_command('withdraw_claim',$k,function()use($r){return GCU_Plugin::instance()->repository()->withdraw_claim($r['claim_key'],absint($r->get_param('expected_version')),sanitize_textarea_field($r->get_param('reason')));});return is_wp_error($x)?$x:$this->no_store(rest_ensure_response($x));}
public function transition(WP_REST_Request$r){$k=$this->required_idempotency_key($r);if(is_wp_error($k)){return$k;}$x=GCU_Plugin::instance()->repository()->run_idempotent_command('transition_'.sanitize_key($r['machine']),$k,function()use($r){return GCU_Plugin::instance()->repository()->transition($r['machine'],$r['public_id'],absint($r->get_param('expected_version')),sanitize_key($r->get_param('target')),sanitize_textarea_field($r->get_param('reason')));});return is_wp_error($x)?$x:$this->no_store(rest_ensure_response($x));}
public function funnel(WP_REST_Request$r){$x=GCU_Plugin::instance()->repository()->funnel_summary(absint($r->get_param('days')?:30));return is_wp_error($x)?$x:$this->no_store(rest_ensure_response($x));}
public function health(){return$this->no_store(rest_ensure_response(GCU_Plugin::instance()->observability()->health_report()));}
public function can_issue_event_token(){if(!GCU_Privacy::measurement_allowed()){return new WP_Error('gcu_measurement_not_allowed',__('Measurement is not permitted in this context.','global-clinic-usp-integration'),array('status'=>403));}return true;}
public function verify_event_token(WP_REST_Request$r){if(!GCU_Privacy::measurement_allowed()){return new WP_Error('gcu_measurement_not_allowed',__('Measurement is not permitted in this context.','global-clinic-usp-integration'),array('status'=>403));}return GCU_Plugin::instance()->repository()->consume_event_token(sanitize_text_field((string)$r->get_header('X-GCU-Event-Token')),'measurement');}
private function required_idempotency_key(WP_REST_Request$r){$k=GCU_Hardening::bounded_text(sanitize_text_field((string)$r->get_header(self::IDEMPOTENCY_HEADER)),191);return strlen($k)<8?new WP_Error('gcu_idempotency_key_required',__('A stable idempotency key is required for this mutation.','global-clinic-usp-integration'),array('status'=>400)):$k;}
private function cache_public_response(WP_REST_Response$r,$s){$s=max(0,min(600,absint($s)));$r->header('Cache-Control','public, max-age='.$s.', stale-while-revalidate=60');$r->header('ETag','"'.hash('sha256',wp_json_encode($r->get_data())).'"');$r->header('Vary','Accept-Language');return$r;}
private function no_store($r){if($r instanceof WP_REST_Response){$r->header('Cache-Control','no-store, private');$r->header('Pragma','no-cache');}return$r;}
public function can_manage_content(){return GCU_Capabilities::can(GCU_Capabilities::MANAGE_CONTENT,null,'rest_content');}public function can_manage_workflow(WP_REST_Request$r){$m=sanitize_key($r['machine']);$cap='copy'===$m?GCU_Capabilities::MANAGE_CONTENT:('placement'===$m?GCU_Capabilities::MANAGE_PLACEMENTS:GCU_Capabilities::MANAGE_EXPERIMENTS);return GCU_Capabilities::can($cap,$r['public_id'],'rest_transition');}public function can_manage_placements(){return GCU_Capabilities::can(GCU_Capabilities::MANAGE_PLACEMENTS,null,'rest_placements');}public function can_manage_experiments(){return GCU_Capabilities::can(GCU_Capabilities::MANAGE_EXPERIMENTS,null,'rest_experiments');}public function can_approve_claims(WP_REST_Request$r){return GCU_Capabilities::can(GCU_Capabilities::APPROVE_CLAIMS,$r['claim_key'],'rest_claim_withdrawal');}public function can_view_analytics(){return GCU_Capabilities::can(GCU_Capabilities::VIEW_ANALYTICS,null,'rest_analytics');}public function can_system_check(){return GCU_Capabilities::can(GCU_Capabilities::SYSTEM_CHECK,null,'rest_health');}
}
