<?php

defined('ABSPATH')||exit;
final class GCU_Contracts{
const STATE_PREFIX='gcu_destination_state_',REVALIDATION_OPTION='gcu_policy_revalidation_required';
public function hooks(){add_action('DoctorDirectoryAvailable.v1',array($this,'consume_directory_event'),10,1);add_action('ClinicBookingAvailable.v1',array($this,'consume_clinic_event'),10,1);add_action('DoctorOnboardingAvailable.v1',array($this,'consume_onboarding_event'),10,1);add_action('BusinessPolicyChanged.v1',array($this,'consume_business_policy_event'),10,1);}
public function destination_registry(){return array('doctor_directory'=>array('owner'=>'File 07','contract'=>'DoctorDirectoryAvailable.v1','fallback_url'=>home_url('/doctors/')),'clinic'=>array('owner'=>'File 08','contract'=>'ClinicBookingAvailable.v1','fallback_url'=>home_url('/worldwide-clinic/')),'doctor_onboarding'=>array('owner'=>'File 09','contract'=>'DoctorOnboardingAvailable.v1','fallback_url'=>home_url('/doctor/apply/')),'how_it_works'=>array('owner'=>'File 14','contract'=>'local','fallback_url'=>home_url('/clinic/how-it-works/')));}
public function destination($key){$key=sanitize_key($key);$reg=$this->destination_registry();if(!isset($reg[$key])){return array('key'=>$key,'owner'=>'','available'=>false,'url'=>'','reason'=>'unknown_destination','contract'=>'');}$def=$reg[$key];if('File 14'===$def['owner']){return array('key'=>$key,'owner'=>$def['owner'],'available'=>(bool)get_option('gcu_enabled',1),'url'=>GCU_Hardening::strict_same_origin_url($def['fallback_url']),'reason'=>get_option('gcu_enabled',1)?'ready':'module_disabled','contract'=>$def['contract']);}$state=get_option(self::STATE_PREFIX.$key,array());$state=is_array($state)?$state:array();$available=!empty($state['available'])&&!empty($state['verified_at'])&&(int)$state['verified_at']>=time()-DAY_IN_SECONDS;$url=!empty($state['url'])?GCU_Hardening::strict_same_origin_url($state['url']):'';if(!$url){$url=GCU_Hardening::strict_same_origin_url($def['fallback_url']);}$filtered=apply_filters('gcu_destination_contract_v1',array('available'=>$available,'url'=>$url,'reason'=>$available?'owner_confirmed':'owner_unconfirmed'),$key,$def);if(is_array($filtered)){if(array_key_exists('available',$filtered)&&false===(bool)$filtered['available']){$available=false;}if(!empty($filtered['url'])){$safe=GCU_Hardening::strict_same_origin_url($filtered['url']);if($safe){$url=$safe;}}}if(!$url){$available=false;}return array('key'=>$key,'owner'=>$def['owner'],'available'=>$available,'url'=>$url,'reason'=>$available?'owner_confirmed':(!empty($state['reason'])?sanitize_key($state['reason']):'owner_unconfirmed'),'contract'=>$def['contract'],'verified_at'=>!empty($state['verified_at'])?(int)$state['verified_at']:0);}
public function all_destination_health(){$out=array();foreach(array_keys($this->destination_registry())as$key){$out[$key]=$this->destination($key);}return$out;}
public function placement_ready(array$p){$slot=sanitize_key(isset($p['slot_key'])?$p['slot_key']:'');$route=sanitize_key(isset($p['route_key'])?$p['route_key']:'');if('global_clinic'!==$route||!in_array($slot,array('global_clinic_primary','global_clinic_trust','global_clinic_steps','global_clinic_faq'),true)){return false;}$ready=apply_filters('sabri_shell_slot_ready_v1',null,$route,$slot,'File 14');if(null===$ready){$ready=apply_filters('gcu_file20_slot_ready_v1',null,$route,$slot);}return true===$ready;}
public function consume_directory_event($p){$this->consume_event('DoctorDirectoryAvailable.v1',$p);}public function consume_clinic_event($p){$this->consume_event('ClinicBookingAvailable.v1',$p);}public function consume_onboarding_event($p){$this->consume_event('DoctorOnboardingAvailable.v1',$p);}public function consume_business_policy_event($p){$this->consume_event('BusinessPolicyChanged.v1',$p);}
private function consume_event($name,$p){if(!is_array($p)){return false;}return GCU_Plugin::instance()->repository()->accept_inbound_event($name,$p);}
public function apply_inbound_event($name,array$p){$map=array('DoctorDirectoryAvailable.v1'=>'doctor_directory','ClinicBookingAvailable.v1'=>'clinic','DoctorOnboardingAvailable.v1'=>'doctor_onboarding');if(isset($map[$name])){$key=$map[$name];$url=!empty($p['url'])?GCU_Hardening::strict_same_origin_url($p['url']):'';if(!empty($p['available'])&&!$url){return new WP_Error('gcu_owner_event_url_invalid',__('Owner readiness cannot be accepted without a safe same-origin URL.','global-clinic-usp-integration'));}$r=array('available'=>!empty($p['available']),'url'=>$url,'reason'=>!empty($p['available'])?'owner_event_ready':'owner_event_unavailable','contract_version'=>isset($p['contract_version'])?max(1,absint($p['contract_version'])):1,'verified_at'=>time(),'event_id'=>sanitize_text_field($p['event_id']));update_option(self::STATE_PREFIX.$key,$r,false);return true;}if('BusinessPolicyChanged.v1'===$name){return$this->queue_policy_revalidation($p);}return new WP_Error('gcu_owner_event_unknown',__('Unknown owner event.','global-clinic-usp-integration'));}
private function queue_policy_revalidation(array$p){$current=get_option(self::REVALIDATION_OPTION,array());$current=is_array($current)?$current:array();$id=sanitize_text_field(isset($p['event_id'])?$p['event_id']:'');if(!$id){return new WP_Error('gcu_policy_event_invalid',__('Policy event identity is required.','global-clinic-usp-integration'));}$current[$id]=array('event_id'=>$id,'policy_version'=>GCU_Hardening::bounded_text(sanitize_text_field(isset($p['policy_version'])?$p['policy_version']:''),64),'changed_keys'=>isset($p['changed_keys'])&&is_array($p['changed_keys'])?array_slice(array_values(array_unique(array_filter(array_map('sanitize_key',$p['changed_keys'])))),0,50):array(),'received_at'=>time());if(count($current)>100){uasort($current,static function($a,$b){return(int)$a['received_at']<=>(int)$b['received_at'];});$current=array_slice($current,-100,null,true);}update_option(self::REVALIDATION_OPTION,$current,false);do_action('gcu_policy_revalidation_queued_v1',$current[$id]);return true;}
}
