<?php

defined('ABSPATH')||exit;
final class GCU_Frontend{
private$current_route='',$degraded_destination='';private static$instance_counter=0;
public function hooks(){add_action('init',array($this,'rewrites'));add_filter('query_vars',array($this,'query_vars'));add_action('template_redirect',array($this,'route_actions'),1);add_action('send_headers',array($this,'cache_headers'),20,0);add_filter('template_include',array($this,'template'),99);add_action('wp_enqueue_scripts',array($this,'assets'));add_action('wp_head',array($this,'head_meta'),1);add_shortcode('gcu_global_clinic',array($this,'shortcode_global_clinic'));add_shortcode('gcu_how_it_works',array($this,'shortcode_how_it_works'));add_shortcode('gcu_block',array($this,'shortcode_block'));}
public function rewrites(){add_rewrite_rule('^global-clinic/?$','index.php?gcu_route=global_clinic','top');add_rewrite_rule('^clinic/how-it-works/?$','index.php?gcu_route=how_it_works','top');add_rewrite_rule('^find-a-global-doctor/?$','index.php?gcu_route=find_doctor','top');add_rewrite_rule('^start-your-global-clinic/?$','index.php?gcu_route=start_clinic','top');}
public function query_vars($v){$v[]='gcu_route';return$v;}
public function route_actions(){$this->current_route=sanitize_key((string)get_query_var('gcu_route'));if(!$this->current_route){return;}$ready=GCU_Install::ready_for_runtime();if(is_wp_error($ready)){$this->degraded_destination=sanitize_key($ready->get_error_code());status_header(503);return;}$m=array('find_doctor'=>'doctor_directory','start_clinic'=>'doctor_onboarding');if(isset($m[$this->current_route])){$h=GCU_Plugin::instance()->contracts()->destination($m[$this->current_route]);if(!empty($h['available'])&&!empty($h['url'])){wp_safe_redirect($h['url'],302,'File 14 canonical destination bridge');exit;}$this->degraded_destination=$m[$this->current_route];status_header(503);}}
public function cache_headers(){$r=sanitize_key((string)get_query_var('gcu_route'));if($r){header('Cache-Control: public, no-cache, max-age=0, must-revalidate',true);header('Pragma: no-cache',true);}}
public function template($t){if(!$this->current_route){$this->current_route=sanitize_key((string)get_query_var('gcu_route'));}return$this->current_route?GCU_DIR.'templates/public-page.php':$t;}
public function assets(){$route=sanitize_key((string)get_query_var('gcu_route'));global$post;$sc=$post instanceof WP_Post&&(has_shortcode($post->post_content,'gcu_global_clinic')||has_shortcode($post->post_content,'gcu_how_it_works')||has_shortcode($post->post_content,'gcu_block'));if(!$route&&!$sc){return;}wp_enqueue_style('gcu-public',GCU_URL.'assets/css/global-clinic-usp-integration.css',array(),GCU_VERSION);if(!is_wp_error(GCU_Install::ready_for_runtime())&&GCU_Privacy::measurement_allowed()&&!GCU_Privacy::low_bandwidth_requested()){wp_enqueue_script('gcu-public',GCU_URL.'assets/js/global-clinic-usp-integration.js',array(),GCU_VERSION,true);wp_localize_script('gcu-public','GCU_PUBLIC',array('tokenEndpoint'=>esc_url_raw(rest_url('gcu/v1/event-token')),'eventEndpoint'=>esc_url_raw(rest_url('gcu/v1/events')),'consent'=>true));}}
public function head_meta(){$r=sanitize_key((string)get_query_var('gcu_route'));if(!$r){return;}if($this->degraded_destination){echo"<meta name=\"robots\" content=\"noindex,nofollow\">\n";return;}$c='how_it_works'===$r?home_url('/clinic/how-it-works/'):home_url('/global-clinic/');echo'<link rel="canonical" href="'.esc_url($c).'">'."\n";}
public function render_route(){$r=$this->current_route?$this->current_route:sanitize_key((string)get_query_var('gcu_route'));$ready=GCU_Install::ready_for_runtime();if($this->degraded_destination||is_wp_error($ready)){return$this->render_degraded($this->degraded_destination?$this->degraded_destination:(is_wp_error($ready)?sanitize_key($ready->get_error_code()):'module_unready'));}return'how_it_works'===$r?$this->render_how_it_works():$this->render_global_clinic();}
public function shortcode_global_clinic(){$ready=GCU_Install::ready_for_runtime();return is_wp_error($ready)?$this->render_degraded(sanitize_key($ready->get_error_code())):$this->render_global_clinic();}public function shortcode_how_it_works(){$ready=GCU_Install::ready_for_runtime();return is_wp_error($ready)?$this->render_degraded(sanitize_key($ready->get_error_code())):$this->render_how_it_works();}
public function shortcode_block($a){$ready=GCU_Install::ready_for_runtime();if(is_wp_error($ready)){return$this->render_degraded(sanitize_key($ready->get_error_code()));}$a=shortcode_atts(array('slot'=>'global_clinic_primary','audience'=>'all'),$a,'gcu_block');return$this->render_blocks(sanitize_key($a['slot']),GCU_Policy::sanitize_audience($a['audience']));}
public function render_primary_slot(){return$this->render_blocks('global_clinic_primary','all');}public function render_trust_slot(){return$this->render_blocks('global_clinic_trust','all');}
public function render_global_clinic(){$l=$this->current_locale();$root=$this->root_id('global-clinic');$h=$this->root_open($root,$l).$this->navigation_controls('global_clinic',$l);$h.='<header class="gcu-page__header"><span class="gcu-eyebrow">'.$this->icon('globe').esc_html(GCU_I18n::text('worldwide_clinic',$l)).'</span><h1>'.esc_html(GCU_I18n::text('hero_title',$l)).'</h1><p>'.esc_html(GCU_I18n::text('hero_body',$l)).'</p></header>';$h.=$this->render_blocks('global_clinic_primary','all').$this->render_blocks('global_clinic_trust','all').$this->render_blocks('global_clinic_steps','all').$this->render_faqs($root,$l).$this->emergency_notice($l).'</div>';return$h;}
public function render_how_it_works(){$l=$this->current_locale();$root=$this->root_id('how-it-works');$c=GCU_Plugin::instance()->contracts();$p=$c->destination('doctor_directory');$d=$c->destination('doctor_onboarding');$h=$this->root_open($root,$l).$this->navigation_controls('how_it_works',$l);$h.='<header class="gcu-page__header"><span class="gcu-eyebrow">'.$this->icon('route').esc_html(GCU_I18n::text('transparent_process',$l)).'</span><h1>'.esc_html(GCU_I18n::text('how_title',$l)).'</h1></header><section class="gcu-journeys" aria-label="'.esc_attr(GCU_I18n::text('journeys_label',$l)).'">';$h.=$this->journey_card(GCU_I18n::text('for_patients',$l),array(GCU_I18n::text('patient_step_1',$l),GCU_I18n::text('patient_step_2',$l),GCU_I18n::text('patient_step_3',$l),GCU_I18n::text('patient_step_4',$l)),$p,GCU_I18n::text('find_doctor',$l),'patient',$l);$h.=$this->journey_card(GCU_I18n::text('for_doctors',$l),array(GCU_I18n::text('doctor_step_1',$l),GCU_I18n::text('doctor_step_2',$l),GCU_I18n::text('doctor_step_3',$l),GCU_I18n::text('doctor_step_4',$l)),$d,GCU_I18n::text('start_clinic',$l),'doctor',$l);return$h.'</section>'.$this->render_faqs($root,$l).$this->emergency_notice($l).'</div>';}
public function render_blocks($slot,$aud){$l=$this->current_locale();$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,$l);if(!$rows&&'en-US'!==$l){$rows=GCU_Plugin::instance()->repository()->active_blocks($slot,$aud,'en-US');}if(!$rows){return'<section class="gcu-state gcu-state--empty" role="status" aria-live="polite"><h2>'.esc_html(GCU_I18n::text('content_review_title',$l)).'</h2><p>'.esc_html(GCU_I18n::text('content_review_body',$l)).'</p></section>';}$h='<section class="gcu-grid gcu-grid--'.esc_attr($slot).'">';foreach($rows as$row){$health=!empty($row['cta_destination'])?GCU_Plugin::instance()->contracts()->destination($row['cta_destination']):array('available'=>false,'url'=>'');$claims=GCU_Plugin::instance()->repository()->public_claims($row['claim_keys']);$h.='<article class="gcu-card gcu-card--'.esc_attr($row['block_type']).'" data-block-version="'.esc_attr($row['content_version']).'"><div class="gcu-card__icon" aria-hidden="true">'.$this->icon('patient'===$row['audience']?'search':('doctor'===$row['audience']?'clinic':'shield')).'</div><h2>'.esc_html($row['title']).'</h2><div class="gcu-card__body">'.wp_kses_post(wpautop($row['body'])).'</div>';if($row['cta_label']){if(!empty($health['available'])&&!empty($health['url'])){$h.='<a class="gcu-button" href="'.esc_url($health['url']).'" data-gcu-destination="'.esc_attr($row['cta_destination']).'">'.$this->icon('arrow',true).'<span>'.esc_html($row['cta_label']).'</span></a>';}else{$h.='<p class="gcu-destination-state" role="status" aria-live="polite">'.$this->icon('info').'<span>'.esc_html(GCU_I18n::text('destination_unavailable',$l)).'</span></p>';}}if($claims){$h.='<details class="gcu-claims"><summary>'.esc_html(GCU_I18n::text('trust_policy_details',$l)).'</summary><ul>';foreach($claims as$claim){$h.='<li>'.esc_html(GCU_Policy::localized_claim_text($claim['claim_key'],$l,$claim['claim_text'])).'</li>';}$h.='</ul></details>';}$h.='</article>';}return$h.'</section>';}
public function current_locale(){return GCU_I18n::current_locale();}
private function render_faqs($root,$l){$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all',$l);if(!$items&&'en-US'!==$l){$items=GCU_Plugin::instance()->repository()->active_blocks('global_clinic_faq','all','en-US');}if(!$items){return'';}$id=$root.'-faq-title';$h='<section class="gcu-faq" aria-labelledby="'.esc_attr($id).'"><h2 id="'.esc_attr($id).'">'.$this->icon('question').esc_html(GCU_I18n::text('faq_title',$l)).'</h2>';foreach($items as$i){$h.='<details data-block-version="'.esc_attr($i['content_version']).'"><summary>'.esc_html($i['title']).'</summary><div>'.wp_kses_post(wpautop($i['body'])).'</div></details>';}return$h.'</section>';}
private function journey_card($title,array$steps,array$health,$label,$aud,$l){$h='<article class="gcu-card gcu-card--journey"><div class="gcu-card__icon" aria-hidden="true">'.$this->icon('patient'===$aud?'search':'clinic').'</div><h2>'.esc_html($title).'</h2><ol>';foreach($steps as$s){$h.='<li>'.esc_html($s).'</li>';}$h.='</ol>';if(!empty($health['available'])&&!empty($health['url'])){$h.='<a class="gcu-button" href="'.esc_url($health['url']).'" data-gcu-destination="'.esc_attr($health['key']).'">'.$this->icon('arrow',true).'<span>'.esc_html($label).'</span></a>';}else{$h.='<p class="gcu-destination-state" role="status" aria-live="polite">'.$this->icon('info').'<span>'.esc_html(GCU_I18n::text('owner_unavailable',$l)).'</span></p>';}return$h.'</article>';}
private function render_degraded($dest){$l=$this->current_locale();$root=$this->root_id('degraded');return$this->root_open($root,$l).$this->navigation_controls('degraded',$l).'<section class="gcu-state gcu-state--error" role="alert" aria-live="assertive"><div class="gcu-state__icon" aria-hidden="true">'.$this->icon('info').'</div><h1>'.esc_html(GCU_I18n::text('service_unavailable',$l)).'</h1><p>'.esc_html(GCU_I18n::text('degraded_body',$l)).'</p><p><code>'.esc_html(sanitize_key($dest)).'</code></p></section></div>';}
private function emergency_notice($l){return'<aside class="gcu-emergency" role="note">'.$this->icon('alert').'<div><strong>'.esc_html(GCU_I18n::text('emergency_title',$l)).'</strong><p>'.esc_html(GCU_I18n::text('emergency_body',$l)).'</p></div></aside>';}
private function navigation_controls($context,$l){$shared=apply_filters('sabri_shell_back_home_controls','',array('owner'=>'File 14','home_url'=>home_url('/'),'fallback_url'=>home_url('/global-clinic/'),'direction'=>GCU_I18n::direction($l)));if(is_string($shared)&&''!==trim($shared)){return$shared;}$back='global_clinic'===$context?home_url('/'):home_url('/global-clinic/');return'<nav class="gcu-context-nav" data-gcu-shell-fallback="true" aria-label="'.esc_attr(GCU_I18n::text('page_navigation',$l)).'"><a href="'.esc_url($back).'">'.$this->icon('back',true).'<span>'.esc_html(GCU_I18n::text('back',$l)).'</span></a><a href="'.esc_url(home_url('/')).'" rel="home">'.$this->icon('home').'<span>'.esc_html(GCU_I18n::text('home',$l)).'</span></a></nav>';}
private function root_open($root,$l){$a=' id="'.esc_attr($root).'" lang="'.esc_attr(GCU_I18n::language($l)).'" dir="'.esc_attr(GCU_I18n::direction($l)).'" data-gcu-module-version="'.esc_attr(GCU_VERSION).'"';if(GCU_Privacy::low_bandwidth_requested()){$a.=' data-gcu-low-bandwidth="true"';}return'<div class="gcu-page"'.$a.'>';}
private function root_id($c){self::$instance_counter++;return'gcu-'.sanitize_html_class($c).'-'.self::$instance_counter;}
private function icon($name,$directional=false){$p=array('globe'=>'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"/>','route'=>'<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a3 3 0 0 0 3-3v-6a3 3 0 0 1 3-3"/>','search'=>'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>','clinic'=>'<path d="M4 21V8l8-5 8 5v13M9 21v-6h6v6M9 10h6M12 7v6"/>','shield'=>'<path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>','arrow'=>'<path d="M5 12h14M14 7l5 5-5 5"/>','info'=>'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>','question'=>'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.7 2.7 0 1 1 4.1 2.3c-1 .6-1.6 1.1-1.6 2.2M12 17h.01"/>','alert'=>'<path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5M12 17h.01"/>','back'=>'<path d="m15 18-6-6 6-6"/>','home'=>'<path d="m3 11 9-8 9 8v10h-6v-6H9v6H3V11Z"/>');$path=isset($p[$name])?$p[$name]:$p['info'];$class='gcu-icon'.($directional?' gcu-icon--directional':'');return'<svg class="'.esc_attr($class).'" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'.$path.'</svg>';}
}
